window.EB=window.EB||{};EB.EventUtil=function(){return{addHandler:function(c,d,e){if(c.addEventListener)c.addEventListener(d,e,false);else if(c.attachEvent)c.attachEvent("on"+d,e);else c["on"+d]=e},removeHandler:function(c,d,e){if(c.removeEventListener)c.removeEventListener(d,e,false);else if(c.detachEvent)c.detachEvent("on"+d,e);else c["on"+d]=null},getEvent:function(c){return c?c:window.event},getTarget:function(c){return c.target||c.srcElement}}}();this.JSON||(JSON=function(){function c(l){return l<10?"0"+l:l}function d(l){j.lastIndex=0;return j.test(l)?'"'+l.replace(j,function(p){var k=q[p];if(typeof k==="string")return k;return"\\u"+("0000"+(+p.charCodeAt(0)).toString(16)).slice(-4)})+'"':'"'+l+'"'}function e(l,p){var k,m,r,t,s=g,o,h=p[l];if(h&&typeof h==="object"&&typeof h.toJSON==="function")h=h.toJSON(l);if(typeof u==="function")h=u.call(p,l,h);switch(typeof h){case "string":return d(h);case "number":return isFinite(h)?String(h):"null";
case "boolean":case "null":return String(h);case "object":if(!h)return"null";g+=n;o=[];if(typeof h.length==="number"&&!h.propertyIsEnumerable("length")){t=h.length;for(k=0;k<t;k+=1)o[k]=e(k,h)||"null";r=o.length===0?"[]":g?"[\n"+g+o.join(",\n"+g)+"\n"+s+"]":"["+o.join(",")+"]";g=s;return r}if(u&&typeof u==="object"){t=u.length;for(k=0;k<t;k+=1){m=u[k];if(typeof m==="string")if(r=e(m,h))o.push(d(m)+(g?": ":":")+r)}}else for(m in h)if(Object.hasOwnProperty.call(h,m))if(r=e(m,h))o.push(d(m)+(g?": ":
":")+r);r=o.length===0?"{}":g?"{\n"+g+o.join(",\n"+g)+"\n"+s+"}":"{"+o.join(",")+"}";g=s;return r}}Date.prototype.toJSON=function(){return this.getUTCFullYear()+"-"+c(this.getUTCMonth()+1)+"-"+c(this.getUTCDate())+"T"+c(this.getUTCHours())+":"+c(this.getUTCMinutes())+":"+c(this.getUTCSeconds())+"Z"};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var f=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
j=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,g,n,q={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},u;return{stringify:function(l,p,k){var m;n=g="";if(typeof k==="number")for(m=0;m<k;m+=1)n+=" ";else if(typeof k==="string")n=k;if((u=p)&&typeof p!=="function"&&(typeof p!=="object"||typeof p.length!=="number"))throw Error("JSON.stringify");return e("",{"":l})},parse:function(l,p){function k(r,
t){var s,o,h=r[t];if(h&&typeof h==="object")for(s in h)if(Object.hasOwnProperty.call(h,s)){o=k(h,s);if(o!==undefined)h[s]=o;else delete h[s]}return p.call(r,t,h)}var m;f.lastIndex=0;if(f.test(l))l=l.replace(f,function(r){return"\\u"+("0000"+(+r.charCodeAt(0)).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(l.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){m=eval("("+l+")");return typeof p===
"function"?k({"":m},""):m}throw new SyntaxError("JSON.parse");}}}());var GLOBAL_LIMIT_DATE=2037,GLOBAL_DEFAULT_LIMIT_DATE="01/01/2037",GLOBAL_DISPLAY_CALENDAR=false,GLOBAL_MODE_DATE="",GLOBAL_MAX_INTEGER=1E6,GLOBAL_MAX_QUANTITY=1E4,GLOBAL_RED="DC143C",GLOBAL_BLACK="000000",GLOBAL_DAY_SECOND=86400,GLOBAL_HOUR_SECOND=3600,GLOBAL_MN_SECOND=60,GLOBAL_ID_MESSAGE="",GLOBAL_ID_MESSAGE_SOURCE="",GLOBAL_TIMEOUT_MESSAGE=3E3,GLOBAL_API_KEY_UPPERCASE=true,GLOBAL_API_KEY_LENGTH=16,GLOBAL_API_KEY_NUMBER=true,gMonth_names_fr={},gMonth_names_us={},gMonth_days={};
gMonth_days["01"]=31;gMonth_days["1"]=31;gMonth_days["02"]=28;gMonth_days["2"]=28;gMonth_days["03"]=31;gMonth_days["3"]=31;gMonth_days["04"]=30;gMonth_days["4"]=30;gMonth_days["05"]=31;gMonth_days["5"]=31;gMonth_days["06"]=30;gMonth_days["6"]=30;gMonth_days["07"]=31;gMonth_days["7"]=31;gMonth_days["08"]=31;gMonth_days["8"]=31;gMonth_days["09"]=30;gMonth_days["9"]=30;gMonth_days["10"]=31;gMonth_days["11"]=30;gMonth_days["12"]=31;gMonth_names_fr["01"]="Janvier";gMonth_names_fr["1"]="Janvier";
gMonth_names_fr["02"]="F\u00e9vrier";gMonth_names_fr["2"]="F\u00e9vrier";gMonth_names_fr["03"]="Mars";gMonth_names_fr["3"]="Mars";gMonth_names_fr["04"]="Avril";gMonth_names_fr["4"]="Avril";gMonth_names_fr["05"]="Mai";gMonth_names_fr["5"]="Janvier";gMonth_names_fr["06"]="Juin";gMonth_names_fr["6"]="Juin";gMonth_names_fr["07"]="Juillet";gMonth_names_fr["7"]="Janvier";gMonth_names_fr["08"]="Ao\u00fbt";gMonth_names_fr["8"]="Ao\u00fbt";gMonth_names_fr["09"]="Septembre";gMonth_names_fr["9"]="Septembre";
gMonth_names_fr["10"]="Octobre";gMonth_names_fr["11"]="Novembre";gMonth_names_fr["12"]="D\u00e9cembre";gMonth_names_us["01"]="January";gMonth_names_us["1"]="January";gMonth_names_us["02"]="February";gMonth_names_us["2"]="February";gMonth_names_us["03"]="March";gMonth_names_us["3"]="March";gMonth_names_us["04"]="April";gMonth_names_us["4"]="April";gMonth_names_us["05"]="May";gMonth_names_us["5"]="May";gMonth_names_us["06"]="June";gMonth_names_us["6"]="June";gMonth_names_us["07"]="July";
gMonth_names_us["7"]="July";gMonth_names_us["08"]="August";gMonth_names_us["8"]="August";gMonth_names_us["09"]="September";gMonth_names_us["9"]="September";gMonth_names_us["10"]="October";gMonth_names_us["11"]="November";gMonth_names_us["12"]="December";function BisexYear(c,d){return c%4==0&&d==2?true:false}function nbDaysPerMonth(c,d){var e=gMonth_days[c];BisexYear(d,c)&&e++;return e}function getMonthName(c,d){switch(d){case "FR":return gMonth_names_fr[c];case "US":return gMonth_names_us[c]}}
function PadDigits(c,d){c=c.toString();var e="";if(d>c.length)for(i=0;i<d-c.length;i++)e+="0";return e+c.toString()}function CountCar(c,d,e){return c.split(d).length-1>e?true:false}function IsNumeric(c){var d,e=true;if(c.length==0)return false;for(i=0;i<c.length&&e==true;i++){d=c.charAt(i);if("0123456789.-".indexOf(d)==-1)e=false}return e}
function checkInteger(c){newVal=parseInt(c.value);if(isNaN(newVal)){alert(gettext("Please enter an integer value."));c.value=0;c.focus()}else c.value=newVal;return false}
function CheckNumeric(c,d,e,f,j){var g=document.getElementById(c).value;g=g.replace(",","");document.getElementById(c).value=g;var n=0;if(d=="F"){reg=/[^0-9.]/i;n=1}else reg=/[^0-9]/i;n=CountCar(g,".",n);var q=GLOBAL_MAX_INTEGER;if(e)q=e;if(!reg.test(g)&&!n)if(parseInt(g)>q&&q>0){alert(gettext("Numbers must be less or equal to")+" "+q+".");document.getElementById(c).value=q;document.getElementById(c).focus()}else{document.getElementById(c).style.color="#"+GLOBAL_BLACK;arguments.length>=3&&f&&f(j)}else{document.getElementById(c).style.color=
"#"+GLOBAL_RED;n&&d=="I"?alert(gettext("Please enter integer numbers here.")):alert(gettext("Please enter numbers here."));document.getElementById(c).value=g.substring(0,g.length-1)}}
function CheckNumeric_Localization(c,d,e,f,j){var g=document.getElementById(c).value;g=g.replace(",","");document.getElementById(c).value=g;var n=0;if(d=="F"){reg=/[^0-9.]/i;n=1}else reg=/[^0-9]/i;n=CountCar(g,".",n);var q=GLOBAL_MAX_INTEGER;if(e)q=e;if(!reg.test(g)&&!n)if(parseInt(g)>q&&q>0){display_error_msg("alert","numericlength","register",q);document.getElementById(c).value=q;document.getElementById(c).focus()}else{document.getElementById(c).style.color="#"+GLOBAL_BLACK;arguments.length>=3&&
f&&f(j)}else{document.getElementById(c).style.color="#"+GLOBAL_RED;n&&d=="I"?display_error_msg("alert","numericinteger","register"):display_error_msg("alert","numeric","register");document.getElementById(c).value=g.substring(0,g.length-1)}}
function ShowCalendar(c,d){var e=[];e[0]="2000.01";e[1]=GLOBAL_LIMIT_DATE+".01";GLOBAL_MODE_DATE=c;Date.parse(d)||(d=new Date);Calendar.setup({inputField:c,button:c,eventName:"click",ifFormat:"%m/%d/%Y",align:"Bl",range:e,date:new Date(d),cache:true,electric:false})}
function AddToCalendar(c,d,e,f){d=d+"/calendar.ics?eid="+e+"&calendar="+c;if(f)d+="&date="+f;else if(document.mgform&&document.mgform.selecteddate)if(document.mgform.selecteddate.selectedIndex<1){alert(gettext("Please select the date you would like to attend."));return}else d+="&date="+document.mgform.selecteddate[document.mgform.selecteddate.selectedIndex].value;if(c=="outlook"||c=="ical")document.location.href=d;else window.open(d,"calendar","toolbar=yes, menubar=yes, location=yes, status=yes, scrollbars=yes,resizable=yes, width=800, height=600, left=0, top=0")}
function CheckLimitDate(c){var d=c.getFullYear();c=new Date(c);return d>GLOBAL_LIMIT_DATE?new Date(GLOBAL_DEFAULT_LIMIT_DATE):c}function Show(c,d){if(document.getElementById(c))if(document.getElementById(c).style.display=="none")if(typeof d!="undefined"&&d!="")document.getElementById(c).style.display=d;else document.getElementById(c).style.display="block"}
function Hide(c){if(document.getElementById(c))if(document.getElementById(c).style.display!="none")document.getElementById(c).style.display="none"}function ShowInline(c){if(document.getElementById(c))if(document.getElementById(c).style.display=="none")document.getElementById(c).style.display="inline"}function HideInline(c){if(document.getElementById(c))if(document.getElementById(c).style.display!="none")document.getElementById(c).style.display="none"}
function Toggle(c){if(document.getElementById(c))document.getElementById(c).style.display=="none"?Show(c):Hide(c)}function ToggleDiv(c,d){if(document.getElementById(c))if(document.getElementById(c).style.display=="none")typeof d!="undefined"&&d!=""?Show(c,d):Show(c);else Hide(c)}
function checkEmail(c){if(window.RegExp){if(RegExp("^[0-9a-zA-Z]+([.-]?[0-9a-zA-Z#'+/^`~_-]+)*@[0-9a-zA-Z]+[0-9a-zA-Z.-]*[.]{1}(travel|museum|[a-zA-Z]{2,4})$").test(c))return true}else if(c.indexOf("@")>=0)return true;return false}
function CheckEmailExtended(c){if(document.getElementById(c)){email=document.getElementById(c).value;if(!checkEmail(email)){alert(gettext("This is not a valid email address."));document.getElementById(c).focus();return false}AtPos=email.indexOf("@");StopPos=email.lastIndexOf(".");Message="";if(email==""||AtPos==-1||StopPos==-1||StopPos<AtPos||StopPos-AtPos==1){alert(gettext("This is not a valid email address."));document.getElementById(c).focus();return false}}return true}
function saveEventUrl(){var c=jQuery("#eventshortname").attr("value");if(!CheckShortname(c)&&c)alert(gettext('Your "Personalized Event URL" can only include lowercase letters and numbers'));else{var d=server+"/seteventurl";c="shortname="+c+"&event_id="+jQuery("#event_id").attr("value");jQuery.ajax({url:d,data:c,success:updateEventShortname,error:throwFailure})}}
function saveOrgUrl(){var c=jQuery("#orgshortname").attr("value");if(!CheckShortname(c)&&c)alert(gettext('Your "Personalized Organizer URL" can only include lowercase letters and numbers.'));else{var d=server+"/setorganizerurl";c="shortname="+c+"&org_id="+jQuery("#org_id").attr("value");jQuery.ajax({url:d,data:c,success:updateOrgShortname,error:throwFailure})}}function throwFailure(c){alert(c.responseText)}
function updateOrgShortname(c){c=c?"http://"+c+"."+domain:server+"/org/"+oid;if(style)c+="?s="+style;jQuery("#organizer_url").html('<a href="'+c+'">'+c+"</a>");ToggleDiv("organizer_personalizedurl")}function updateEventShortname(c){c=c?"http://"+c+"."+domain:server+"/event/"+eid;jQuery("#event_url").html('<a href="'+c+'">'+c+"</a>");ToggleDiv("event_personalizedurl")}function CheckShortname(c){if(c=="")return false;return/[^a-z0-9-]/.test(c)?false:true}
function SetCookie(c,d,e){var f=new Date,j=new Date;if(e==null||e==0)e=1;j.setTime(f.getTime()+864E5*e);document.cookie=c+"="+encodeURIComponent(d)+";expires="+j.toGMTString()}function ReadCookie(c){var d=""+document.cookie,e=d.indexOf(c);if(e==-1||c=="")return"";var f=d.indexOf(";",e);if(f==-1)f=d.length;return unescape(d.substring(e+c.length+1,f))}function EraseCookie(c){SetCookie(c,"",-1)}
function TestCookies(){SetCookie("test","1",1);if(ReadCookie("test")=="1"){EraseCookie("test");return true}return false}function ShowDiv(c){if(document.getElementById(c))if(document.getElementById(c).style.display=="none")document.getElementById(c).style.display="block"}function HideDiv(c){if(document.getElementById(c))if(document.getElementById(c).style.display!="none")document.getElementById(c).style.display="none"}
function ShowDivFromCheckbox(c,d){if(c.checked){Show(d);document.getElementById(d).focus()}else{if(d=="channelsDiv"){$("channels").options[0].selected=true;$("channels_2").options[0].selected=true;$("tags").value=""}Hide(d)}}function common_replace_car(c,d,e){var f=c;if(document.getElementById(c))f=document.getElementById(c).value;c=d?d:'"';e=e?e:"'";f=f.split("");for(d=0;d<f.length;d++){wcar=f[d];wcar=wcar.replace(c,e);f[d]=wcar}return f=f.join("")}
function CopyText(c,d){var e=document.getElementById(c),f=document.getElementById(d);if(e!=""&&f!="")f.value=e.value}function ControlDate(c){c=document.getElementById(c);alert(c)}function ValidCheckBox(c){if(document.getElementById(c)){c=document.getElementById(c);var d=c.length,e="";for(i=0;i<d;i++)if(c[i].checked)e=e+c[i].value+" ";if(e==""){Alert("No boxes checked.");return false}return true}}function cGA(c){typeof pageTracker!="undefined"&&pageTracker._trackPageview(c)}
function isInt(c){return c.toString().search(/^-?[0-9]+$/)==0}var STR_PAD_LEFT=1,STR_PAD_RIGHT=2,STR_PAD_BOTH=3;function paddingSTR(c,d,e,f){if(typeof d=="undefined")d=0;if(typeof e=="undefined")e=" ";if(typeof f=="undefined")f=STR_PAD_RIGHT;if(d+1>=c.length)switch(f){case STR_PAD_LEFT:c=Array(d+1-c.length).join(e)+c;break;case STR_PAD_BOTH:d=Math.ceil((padlen=d-c.length)/2);c=Array(padlen-d+1).join(e)+c+Array(d+1).join(e);break;default:c+=Array(d+1-c.length).join(e)}return c}
String.prototype.trim=function(){return this.replace(/^\s+/,"").replace(/\s+$/,"")};function checkHTML(c){var d=e,e=document.getElementById(c).value;try{d=HTMLtoXML(e);if(d.length>254)d=e}catch(f){d=e}document.getElementById(c).value=d;return true}function splitTrim(c,d){if(c.indexOf(d)>=0){for(var e=c.split(d),f=0;f<e.length;f++)e[f]=e[f].trim();c=e.join(d)}return c}function UpperName(c){return c.charAt(0).toUpperCase()+c.substring(1).toLowerCase()}
function Capitalize(c,d){var e=[];if(c.indexOf(d)>=0){var f=c.split(d);for(i=0;i<f.length;i++)e.push(UpperName(f[i]));return e.join(d)}else return c}function extendedCapitalize(c){upperZone=c.trim();if(upperZone.indexOf(",")==-1)upperZone=upperZone.indexOf(" ")>=0?Capitalize(upperZone," "):upperZone.indexOf("-")>=0?Capitalize(upperZone,"-"):UpperName(upperZone);return upperZone}function stripHTML(c){return c.replace(/<&#91;^>&#93;*>/g,"")}
function limiteTextarea(c,d){if(c.value.length<d){a=c.value.split("\n");for(x=b=0;x<a.length;x++)if(a[x].length>=c.cols)b+=Math.floor(a[x].length/c.cols);b+=a.length;c.rows=b}else document.getElementById(c.name).value=c.value.substring(0,d)}
function BuildDateJS(c,d,e,f){if(document.getElementById(c)){c=document.getElementById(c).value;f=document.getElementById(f).value;d=document.getElementById(d).value;e=document.getElementById(e).value;if(f=="PM"){f=parseInt(d,10);if(f<12)f+=12;d=f}else{f=parseInt(d,10);if(f==12)d=0}f="";return new Date(c+(" "+d+":"+e+":00"))}}
function ComputeNewDate(c,d,e,f,j){if(e=="")e="0";if(f=="")f="0";if(j=="")j="0";e=parseInt(e);f=parseInt(f);j=parseInt(j);j=(e*GLOBAL_DAY_SECOND+f*GLOBAL_HOUR_SECOND+j*GLOBAL_MN_SECOND)*1E3;d=new Date(d);c==""||c=="SUB"?d.setTime(d.getTime()-j):d.setTime(d.getTime()+j);e=d.getHours();j=d.getMinutes();c="AM";e=parseInt(e);j=parseInt(j);if(e>12){e-=12;c="PM"}return{date:d.format("MM/DD/YYYY"),hour:PadDigits(e,2),minute:PadDigits(j,2),ampm:c}}
String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")};function unescapeHTMLFixed(c){newVal=new String(c);c=document.createElement("div");c.innerHTML=newVal.replace(/<\/?[^>]+>/gi,"");if(c.childNodes.length<1)return"";newVal=c.childNodes[0].nodeValue;newVal=newVal.replace(/&quot;/gi,'"');return newVal=newVal.replace(/&#39;/gi,"'")}
function isValidURL(c){return/^(([\w]+:)?\/\/)?(([\d\w]|%[a-fA-f\d]{2,2})+(:([\d\w]|%[a-fA-f\d]{2,2})+)?@)?([\d\w][-\d\w]{0,253}[\d\w]\.)+[\w]{2,4}(:[\d]+)?(\/([-+_~.\d\w]|%[a-fA-f\d]{2,2})*)*(\?(&?([-+_~.\d\w]|%[a-fA-f\d]{2,2})=?)*)?(#([-+_~.\d\w]|%[a-fA-f\d]{2,2})*)?$/.test(c)?true:false};
