var ZeroClipboard={version:"1.0.7",clients:{},moviePath:"ZeroClipboard.swf",nextId:1,$:function(a){if(typeof a=="string")a=document.getElementById(a);if(!a.addClass){a.hide=function(){this.style.display="none"};a.show=function(){this.style.display=""};a.addClass=function(b){this.removeClass(b);this.className+=" "+b};a.removeClass=function(b){for(var c=this.className.split(/\s+/),d=-1,e=0;e<c.length;e++)if(c[e]==b){d=e;e=c.length}if(d>-1){c.splice(d,1);this.className=c.join(" ")}return this};a.hasClass=
function(b){return!!this.className.match(RegExp("\\s*"+b+"\\s*"))}}return a},setMoviePath:function(a){this.moviePath=a},dispatch:function(a,b,c){(a=this.clients[a])&&a.receiveEvent(b,c)},register:function(a,b){this.clients[a]=b},getDOMObjectPosition:function(a,b){for(var c={left:0,top:0,width:a.width?a.width:a.offsetWidth,height:a.height?a.height:a.offsetHeight};a&&a!=b;){c.left+=a.offsetLeft;c.top+=a.offsetTop;a=a.offsetParent}return c},Client:function(a){this.handlers={};this.id=ZeroClipboard.nextId++;
this.movieId="ZeroClipboardMovie_"+this.id;ZeroClipboard.register(this.id,this);a&&this.glue(a)}};
ZeroClipboard.Client.prototype={id:0,ready:false,movie:null,clipText:"",handCursorEnabled:true,cssEffects:true,handlers:null,glue:function(a,b,c){this.domElement=ZeroClipboard.$(a);a=99;if(this.domElement.style.zIndex)a=parseInt(this.domElement.style.zIndex,10)+1;if(typeof b=="string")b=ZeroClipboard.$(b);else if(typeof b=="undefined")b=document.getElementsByTagName("body")[0];var d=ZeroClipboard.getDOMObjectPosition(this.domElement,b);this.div=document.createElement("div");var e=this.div.style;e.position=
"absolute";e.left=""+d.left+"px";e.top=""+d.top+"px";e.width=""+d.width+"px";e.height=""+d.height+"px";e.zIndex=a;if(typeof c=="object")for(addedStyle in c)e[addedStyle]=c[addedStyle];b.appendChild(this.div);this.div.innerHTML=this.getHTML(d.width,d.height)},getHTML:function(a,b){var c="",d="id="+this.id+"&width="+a+"&height="+b;if(navigator.userAgent.match(/MSIE/)){var e=location.href.match(/^https/i)?"https://":"http://";c+='<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="'+
e+'download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0" width="'+a+'" height="'+b+'" id="'+this.movieId+'" align="middle"><param name="allowScriptAccess" value="always" /><param name="allowFullScreen" value="false" /><param name="movie" value="'+ZeroClipboard.moviePath+'" /><param name="loop" value="false" /><param name="menu" value="false" /><param name="quality" value="best" /><param name="bgcolor" value="#ffffff" /><param name="flashvars" value="'+d+'"/><param name="wmode" value="transparent"/></object>'}else c+=
'<embed id="'+this.movieId+'" src="'+ZeroClipboard.moviePath+'" loop="false" menu="false" quality="best" bgcolor="#ffffff" width="'+a+'" height="'+b+'" name="'+this.movieId+'" align="middle" allowScriptAccess="always" allowFullScreen="false" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" flashvars="'+d+'" wmode="transparent" />';return c},hide:function(){if(this.div)this.div.style.left="-2000px"},show:function(){this.reposition()},destroy:function(){if(this.domElement&&
this.div){this.hide();this.div.innerHTML="";var a=document.getElementsByTagName("body")[0];try{a.removeChild(this.div)}catch(b){}this.div=this.domElement=null}},reposition:function(a){if(a)(this.domElement=ZeroClipboard.$(a))||this.hide();if(this.domElement&&this.div){a=ZeroClipboard.getDOMObjectPosition(this.domElement);var b=this.div.style;b.left=""+a.left+"px";b.top=""+a.top+"px"}},setText:function(a){this.clipText=a;this.ready&&this.movie.setText(a)},addEventListener:function(a,b){a=a.toString().toLowerCase().replace(/^on/,
"");this.handlers[a]||(this.handlers[a]=[]);this.handlers[a].push(b)},setHandCursor:function(a){this.handCursorEnabled=a;this.ready&&this.movie.setHandCursor(a)},setCSSEffects:function(a){this.cssEffects=!!a},receiveEvent:function(a,b){a=a.toString().toLowerCase().replace(/^on/,"");switch(a){case "load":this.movie=document.getElementById(this.movieId);if(!this.movie){var c=this;setTimeout(function(){c.receiveEvent("load",null)},1);return}if(!this.ready&&navigator.userAgent.match(/Firefox/)&&navigator.userAgent.match(/Windows/)){c=
this;setTimeout(function(){c.receiveEvent("load",null)},100);this.ready=true;return}this.ready=true;this.movie.setText(this.clipText);this.movie.setHandCursor(this.handCursorEnabled);break;case "mouseover":if(this.domElement&&this.cssEffects){this.domElement.addClass("hover");this.recoverActive&&this.domElement.addClass("active")}break;case "mouseout":if(this.domElement&&this.cssEffects){this.recoverActive=false;if(this.domElement.hasClass("active")){this.domElement.removeClass("active");this.recoverActive=
true}this.domElement.removeClass("hover")}break;case "mousedown":this.domElement&&this.cssEffects&&this.domElement.addClass("active");break;case "mouseup":if(this.domElement&&this.cssEffects){this.domElement.removeClass("active");this.recoverActive=false}}if(this.handlers[a])for(var d=0,e=this.handlers[a].length;d<e;d++){var g=this.handlers[a][d];if(typeof g=="function")g(this,b);else if(typeof g=="object"&&g.length==2)g[0][g[1]](this,b);else if(typeof g=="string")window[g](this,b)}}};Array.prototype.max=function(){for(var a=this[0],b=this.length,c=1;c<b;c++)if(this[c]>a)a=this[c];return a};Array.prototype.min=function(){for(var a=this[0],b=this.length,c=1;c<b;c++)if(this[c]<a)a=this[c];return a};Array.prototype.in_array=function(a){for(var b in this)if(this[b]==a)return b;return 0};var ie=navigator.userAgent.indexOf("MSIE")!=-1,ie6=navigator.userAgent.indexOf("MSIE 6.0")!=-1,defaultFieldMessages={},gMinEventDate,gMaxEventDate;defaultFieldMessages.eventName=gettext("Attend This Event");
if(currentWidget=="CALENDAR"||currentWidget=="CALENDAR-IFRAME")gDateEvent=computeMinmaxEventDate();function fixForIE6(){if(ie6)if(currentWidget=="COUNTDOWN"||currentWidget=="COUNTDOWN-IFRAME")document.getElementById("highlight").className="highlight_IE6"}function checkKeyPress(a){if(window.event)a=window.event.keyCode;else if(a)a=a.which;else return true;if(a==13){saveWidgetSettings(gSelectCurrentEID,currentWidget);return false}else return true}
function resetIframe(){document.getElementById("iframeCode").value=""}function dec2hex(a){a=a.toString(16).toUpperCase();return a.length==1?"0"+a:a}function hex2dec(a){return parseInt(a,16)}
function FieldtoHEX(a){a=document.getElementById(a);if(a.style.background.indexOf("rgb")<0)return a.style.background.toUpperCase();rgb=a.style.background.replace(/ /g,"");rgb=rgb.substring(rgb.indexOf("(")+1,rgb.indexOf(")"));rgb=rgb.split(",");return"#"+dec2hex(parseInt(rgb[0]))+dec2hex(parseInt(rgb[1]))+dec2hex(parseInt(rgb[2]))}
function openPicker(a){document.getElementById("iframeCode").value="";YAHOO.example.colorpicker.inDialog.setBoxID(a);a=document.getElementById(a);if(a.style.background.indexOf("#")>=0)rgb=YAHOO.util.Color.hex2rgb(a.style.background.substring(1,7));else{rgb=a.style.background.replace(/ /g,"");rgb=rgb.substring(rgb.indexOf("(")+1,rgb.indexOf(")"));rgb=rgb.split(",")}document.getElementById("yui-picker-panel").style.display="block";YAHOO.example.colorpicker.inDialog.dialog.render();YAHOO.example.colorpicker.inDialog.getPicker().setValue([parseInt(rgb[0]),
parseInt(rgb[1]),parseInt(rgb[2])],false);YAHOO.example.colorpicker.inDialog.dialog.show()}function affectBackgroundColor(a,b){var c=YAHOO.util.Color.hex2rgb(a.replace("#",""));c="rgb("+c[0]+", "+c[1]+", "+c[2]+")";if(b)document.getElementById(b).style.background=c;return c}
function initPicker(){YAHOO.example.colorpicker.inDialog=function(){var a,b="";return{init:function(){this.dialog=new YAHOO.widget.Dialog("yui-picker-panel",{width:"400px",close:true,fixedcenter:true,modal:true,visible:false,constraintoviewport:true,buttons:[{text:gettext("Cancel"),handler:this.handleCancel},{text:gettext("Save"),handler:this.handleSubmit,isDefault:true}]});this.dialog.renderEvent.subscribe(function(){a||(a=new YAHOO.widget.ColorPicker("yui-picker",{container:this.dialog,showcontrols:true,
showhexcontrols:true,showhsvcontrols:false,showwebsafe:false,images:{PICKER_THUMB:"http://developer.yahoo.com/yui/examples/colorpicker/assets/picker_thumb.png",HUE_THUMB:"http://developer.yahoo.com/yui/examples/colorpicker/assets/hue_thumb.png"}}))})},getPicker:function(){return a},getBoxID:function(){return b},setBoxID:function(c){b=c},handleSubmit:function(){hex=a.getElement("yui-picker-hex").value;validHex=/(^(#)?[0-9A-F]{6}$)/i;if(!validHex.test(hex)){alert(gettext("Please enter a 6-digit hex color value."));
return false}rgbColor=affectBackgroundColor(hex,b);if(b=="choose_text_color"){document.getElementById("choose_text_color").style.color=rgbColor;userMessageColor="#"+hex;currentWidget==="BUTTON"&&EB.ButtonWidget.updateColor("textColor",userMessageColor)}if(b=="choose_text_other_color"){document.getElementById("choose_text_other_color").style.color=rgbColor;userTextColor="#"+hex}else if(b=="choose_background_color"){document.getElementById("choose_background_color").style.color=rgbColor;userBackgroundColor=
"#"+hex;currentWidget==="BUTTON"&&EB.ButtonWidget.updateColor("backgroundColor",userBackgroundColor)}else if(b=="choose_thin_color"){document.getElementById("choose_thin_color").style.color=rgbColor;userThinOutlineColor="#"+hex}else if(b=="choose_thick_color"){document.getElementById("choose_thick_color").style.color=rgbColor;userThickOutlineColor="#"+hex}updateWidgetColor();this.cancel()},handleCancel:function(){this.cancel()}}}();YAHOO.util.Event.onDOMReady(YAHOO.example.colorpicker.inDialog.init,
YAHOO.example.colorpicker.inDialog,true)}function checkSettingsUpdate(a){var b=0;switch(a){case "CALENDAR":b=checkColorUpdate(a);if(b==0)b=checkCountDownSelect(a);break;case "COUNTDOWN":b=checkColorUpdate(a);if(b==0)b=checkCountDownSelect(a);break;case "BUTTON":b=checkColorUpdate(a)}b==1&&gClickOnCreateWidget==0&&confirm(gettext("You have not saved changes to your Widget, press Ok to save"))&&embeddedCode()}
function checkCountDownSelect(a){for(var b in gSelectComponent)if(gOriginalSelectComponent[b]!=gSelectComponent[b])return 1;if(a=="CALENDAR")if(gSelectCalendarType!=previousSelectCalendarType)return 1;return 0}
function checkColorUpdate(a){var b=0;switch(a){case "CALENDAR":case "COUNTDOWN":if(previousUserMessageColor!=userMessageColor||previousUserBackgroundColor!=userBackgroundColor||previousUserThinOutlineColor!=userThinOutlineColor||previousUserThickOutlineColor!=userThickOutlineColor||previousUserTextColor!=userTextColor)b=1;break;case "BUTTON":if(previousUserBackgroundColor!=userBackgroundColor||previousUserMessageColor!=userMessageColor||previousTextButtonSize!=textButtonSize||previousTextButtonWidget!=
textButtonWidget)b=1}return b}
function eventColor(){userMessageColor=eventUserMessageColor;userTextColor=eventUserTextColor;userBackgroundColor=eventUserBackgroundColor;userThinOutlineColor=eventUserThinOutlineColor;userThickOutlineColor=eventUserThickOutlineColor;document.getElementById("choose_text_color").style.background=affectBackgroundColor(eventUserMessageColor);document.getElementById("choose_text_other_color").style.background=affectBackgroundColor(eventUserTextColor);document.getElementById("choose_background_color").style.background=affectBackgroundColor(eventUserBackgroundColor);
document.getElementById("choose_thin_color").style.background=affectBackgroundColor(eventUserThinOutlineColor);document.getElementById("choose_thick_color").style.background=affectBackgroundColor(eventUserThickOutlineColor);updateWidgetColor()}
function updateWidgetColor(){switch(currentWidget){case "COUNTDOWN":case "COUNTDOWN-IFRAME":case "CALENDAR-IFRAME":case "CALENDAR":if(currentWidget=="COUNTDOWN"||currentWidget=="CALENDAR"){document.getElementById("widget_text_color").value=userMessageColor;document.getElementById("widget_text_other_color").value=userTextColor;document.getElementById("widget_background_color").value=userBackgroundColor;document.getElementById("widget_thin_outline").value=userThinOutlineColor;document.getElementById("widget_thick_outline").value=
userThickOutlineColor}if(currentWidget=="COUNTDOWN"||currentWidget=="COUNTDOWN-IFRAME"){changeStyle("#ebcountdown","background-color",userThickOutlineColor);changeStyle("#ebcountdown .registernowbutton a:hover","background-color",userThickOutlineColor);changeStyle("#ebcountdown .calshadow","border-bottom","1px "+userThickOutlineColor+" solid");changeStyle("#ebcountdown","border-color",userThickOutlineColor);changeStyle("#ebcountdown .innerbackground","border-color",userThinOutlineColor);changeStyle("#countdown h1",
"color",userThinOutlineColor);changeStyle("#countdown h2","color",userThinOutlineColor);changeStyle("#countdown p","color",userThinOutlineColor);changeStyle("#ebcountdown .calshadow","border-top","1px "+userThinOutlineColor+" solid");changeStyle("#ebcountdown .calshadow","border-bottom","1px "+userThinOutlineColor+" solid");changeStyle("#ebcountdown a, a:active, a:visited","color",userMessageColor);changeStyle("#ebcountdown .registernowbutton a:hover","color",userMessageColor);changeStyle("#ebcountdown .registernowbutton a",
"background-color",userMessageColor);changeStyle("#ebcountdown .innerbackground","background-color",userBackgroundColor);changeStyle("#ebcountdown .registernowbutton a","color",userBackgroundColor);if(currentWidget=="COUNTDOWN")document.getElementById("ebcountdown").style.backgroundColor=userThickOutlineColor}else if(currentWidget=="CALENDAR"||currentWidget=="CALENDAR-IFRAME"){document.getElementById("currentMonth").style.color=userTextColor;updateCalendarNavigation(gCurrentCalendarDate);changeStyle("#monthcontainer a:hover",
"background-color",userThickOutlineColor);changeStyle("#ebcalendar .registernowbutton a:hover","background-color",userThickOutlineColor);document.getElementById("ebcalendar").style.backgroundColor=userThickOutlineColor;if(ie6){document.getElementById("calendarbackground").style.backgroundColor=userBackgroundColor;changeStyle("#ebcalendar","background-color",userBackgroundColor);changeStyle("#calendarbackground","background-color",userBackgroundColor);changeStyle("div>#calendarbackground","background-color",
userBackgroundColor)}else{document.getElementById("calendarbackground").style.backgroundColor=userThickOutlineColor;document.getElementById("calendarbackground").style.borderTop="1px "+userThinOutlineColor+" solid";changeStyle("#ebcalendar","background-color",userThickOutlineColor);changeStyle("#calendarbackground ul li","border-right","1px "+userThickOutlineColor+" solid");changeStyle("#ebcalmultipledates ul","border-bottom","1px "+userThickOutlineColor+" solid");changeStyle("#ebcaleventlist .ebcaleventdivider",
"border-bottom","1px "+userThickOutlineColor+" solid");changeStyle("#ebcalendar .calshadow","border-top","1px "+userThinOutlineColor+" solid")}changeStyle("#ebcalmultipledates ul li a:hover","background-color",userMessageColor);changeStyle("#ebcalendar a, a:active, a:visited, #ebcalmultipledates","color",userMessageColor);changeStyle("#monthcontainer","color",userTextColor);changeStyle("#monthcontainer a:hover","color",userMessageColor);changeStyle("#calendarbackground ul","color",userTextColor);
changeStyle("#calendarbackground ul li a:hover","color",userMessageColor);changeStyle("#calendarbackground ul li a","background-color",userMessageColor);changeStyle("#ebcalendar .registernowbutton a:hover","color",userMessageColor);changeStyle("#ebcalendar .registernowbutton a","background-color",userMessageColor);changeStyle("#ebcalmultipledates h3","color",userTextColor);changeStyle("#ebcalmultipledates h3","border-bottom",userThinOutlineColor);changeStyle("#dayscontainer ul","color",userThinOutlineColor);
changeStyle("#ebcalendar .innerbackground","border","1px "+userThinOutlineColor+" solid");changeStyle("#ebcalmultipledates ul li","border-color",userThinOutlineColor);changeStyle("#ebcaleventlist .ebcaleventdivider","border-top",userThinOutlineColor);changeStyle("#monthcontainer a","background-color",userThinOutlineColor);changeStyle("#monthcontainer a:hover","background-color",userThickOutlineColor);document.getElementById("calendarbackground").style.borderTop="1px "+userThinOutlineColor+" solid";
document.getElementById("calendarbackground").style.borderBottom="1px "+userThinOutlineColor+" solid";changeStyle("#ebcalendar .innerbackground","background-color",userBackgroundColor);changeStyle("#calendarbackground ul li a:hover","background-color",userBackgroundColor);changeStyle("#ebcalendar .registernowbutton a","color",userBackgroundColor);changeStyle("#monthcontainer a","color",userBackgroundColor);changeStyle("#calendarbackground ul li a","color",userBackgroundColor);changeStyle("#ebcalmultipledates ul li a:hover",
"color",userBackgroundColor)}document.getElementById("display_eventname").style.color=userTextColor;document.getElementById("display_eventdate").style.color=userTextColor;document.getElementById("display_eventvenue").style.color=userTextColor;document.getElementById("display_eventlocation").style.color=userTextColor;document.getElementById("display_eventtweeter").style.color=userTextColor;break;case "TEXTLINK":document.getElementById("eventName").style.color=userMessageColor}}
function countDownInitProcess(a){a=="HOURS"&&changeStyle("#countdown h1","font-size","56px")}function setMessage(a){if(a)if(a.value==""||a.value==defaultFieldMessages[a.id]){a.className="textbox_empty";a.value=defaultFieldMessages[a.id]}else a.className="textbox"}function clearMessage(a){if(a&&a.value==defaultFieldMessages[a.id]){a.className="textbox";a.value=""}}function setDefaultFieldMessages(){for(key in defaultFieldMessages)(field=document.getElementById(key))&&setMessage(field)}
var typePadApiKey="52616e646f6d495600c4316be7f79ce474401d6b72fcefdb143b4c5dca07173469f85270b2115ebfa8ecca100cfc4b0170b391b34bafb8bf",wordPressApiKey="09f4a8dfa659";function postMyspace(a,b,c,d){if(c=="CALENDAR"||c=="COUNTDOWN")b+="Simple";b=encodeURIComponent(document.getElementById(b).value+d);a=encodeURIComponent(document.getElementById(a).value);b="http://www.myspace.com/Modules/PostTo/pages/?l=1&u="+b;b+="?t="+a+"&c="+a;window.open(b)}
function postLinkedIn(a,b,c,d){a=document.getElementById(a).value;d=document.getElementById(b).value+d;b=a;if(document.getElementById("descEvent"))b=document.getElementById("descEvent").value;d="http://www.linkedin.com/shareArticle?mini=true&url="+encodeURIComponent(d);d+="&title="+encodeURIComponent(a)+"&source=Eventbrite";d+="&summary="+encodeURIComponent(b);window.open(d)}
function postTwitter(a,b){var c=document.getElementById(a).value;document.getElementById(b);c="http://twitter.com/home?status="+encodeURIComponent(c)+" -- "+encodeURIComponent(gEventUrl+"tw");window.open(c)}function postDigg(a,b,c,d){a=document.getElementById(a).value;b=document.getElementById(b).value+d;b="http://digg.com/submit?phase=2&url="+encodeURIComponent(b);b+="&title="+encodeURIComponent(a);window.open(b)}
function postReddit(a,b,c,d){a=document.getElementById(a).value;b=document.getElementById(b).value+d;b="http://reddit.com/submit?url="+encodeURIComponent(b);b+="&title="+encodeURIComponent(a);window.open(b)}
function postTypePad(a,b,c,d){a=document.getElementById(a).value;b=document.getElementById(b).value+d;d="https://www.typepad.com/t/app/weblog/design/widgets";d+="?service_key="+typePadApiKey;d+="&service=EventBrite";d+="&service_name=EventBrite";d+="&service_url=http://www.eventbrite.com";d+="&return_url=http://www.eventbrite.com";d+="&long_name="+encodeURIComponent(a);d+="&short_name="+encodeURIComponent(a);d+="&content="+encodeURIComponent(b);window.open(d)}
function postFacebook(a,b,c,d){document.getElementById(a);a=document.getElementById(b).value+d;b="http://www.facebook.com/sharer.php";b+="?u="+a;b+="&from_posted=1";window.open(b)}function loginGoogleAccount(){google.load("gdata","1.x",{packages:["blogger"]})}function logMeIn(){scope="http://www.blogger.com/feeds/";googleToken=google.accounts.user.login(scope)}
function setupMyService(){if(!googleMyServices){googleMyServices=new google.gdata.blogger.BloggerService("GoogleInc-jsguide-1.0");logMeIn()}}function getBloggerPost(){googleMyServices.getBlogFeed("http://www.blogger.com/feeds/default/blogs",function(a){a=a.feed.getEntries();if(a.length){a=a[0].getEntryPostLink().getHref();window.open(a,"Your Blog")}},function(a){alert(a)})}
function postBlogger(a,b,c){setupMyService();var d=document.getElementById(a).value,e=document.getElementById(b).value+c,g=function(f){var k=new google.gdata.blogger.BlogPostEntry({title:{type:"text",text:d},content:{type:"text",text:e},categories:[{scheme:"http://www.blogger.com/atom/ns#",term:"Label1"},{scheme:"http://www.blogger.com/atom/ns#",term:"Label2"}]});f.feed.insertEntry(k,function(){alert(interpolate(gettext("The %(current_widget)s's Widget has been successfully posted to Blogger"),{current_widget:currentWidget},
true));getBloggerPost()},j)},j=function(f){alert(f)};googleMyServices.getBlogFeed("http://www.blogger.com/feeds/default/blogs",function(f){f=f.feed.getEntries();if(f.length){f=f[0].getEntryPostLink().getHref();googleMyServices.getBlogPostFeed(f,g,j)}},j)}
function updateCountdownWidget(a,b){var c="display_"+a,d="post_"+a;if(gSelectComponent[a]==1&&!b||gSelectComponent[a]==0&&b){gSelectComponent[a]=0;document.getElementById(c).style.display="none";try{document.getElementById(a).checked=""}catch(e){}}else if(gSelectComponent[a]==0&&!b||gSelectComponent[a]==1&&b){gSelectComponent[a]=1;document.getElementById(c).style.display="block";try{document.getElementById(a).checked="checked"}catch(g){}}document.getElementById(d).value=gSelectComponent[a];if(!b)document.getElementById("iframeCode").value=
""}function initCountDownSelect(){for(var a in gSelectComponent){gOriginalSelectComponent[a]=gSelectComponent[a];if(gSelectComponent[a]==1){if(document.getElementById(a))document.getElementById(""+a).checked="checked"}else if(document.getElementById(a))document.getElementById(""+a).checked=""}}function changeStyle(a,b,c){jQuery(a).css(b,c)}
function initCalendar(a,b,c){var d=new Date(b+"/"+a+"/01"),e=firstWeekDay==0?d.getDay()-1:d.getDay();if(e<0)e+=7;var g=nbDaysPerMonth(a,b);document.getElementById("currentMonth").innerHTML=monthNames[a-1]+" "+b;for(var j=0;j<42;j++){valueDay="day_"+j;document.getElementById(valueDay).innerHTML="";document.getElementById(valueDay).style.display="block"}var f=0;var k=d=0,l="",o={},q={},s=[],v=[],w=[],m=0,t={},u={},n=new Date;n=new Date(n.getFullYear(),n.getMonth(),n.getDate());var r=false;for(j=e;j<
42;j++){m=0;f+=1;if(f<=g){valueDay="day_"+j;currentDayMonth=b+"/"+PadDigits(a,2)+"/"+PadDigits(f,2);idxTabEventdate=gTabEventDate.indexOf(currentDayMonth);if(idxTabEventdate>=0){if(gTabNbrEventDate[idxTabEventdate]>1){idxOrg=searchForOrganizer(gSelectCurrentOrganizer,currentDayMonth);m=1;if(idxOrg>0)idxTabEventdate=idxOrg-1}if(gTabHasPublicEventsDate[idxTabEventdate]==0&&!showPrivateEvents)document.getElementById(valueDay).innerHTML=f;else{e=null;if(c!="")for(var i in gTabEventOrganizerIdReference){l=
gTabEventOrganizerIdReference[i];var h=gTabEventDateReference[i],p=gTabEventDateListReference[i],x=gTabEventListedReference[i];if(showPrivateEvents||x==1)if(l==gFilterByOrganizer)if(h==currentDayMonth||p.indexOf(currentDayMonth)>=0)e=i}else if(c=="")e=gTabEventDatePublicEID[idxTabEventdate];if(e){h={};p=l="";i=e;h.eid=i;h.name=gTabEventReference[i];h.date=currentDayMonth;h.oid=gTabEventOrganizerIdReference[i];h.oname=gTabEventOrganizerReference[i];h.multiEvent=m;h.valueDay=valueDay;h.sig=gTabEventSigReference[i];
t=h;if(!r){e=new Date(currentDayMonth);if(n.getTime()<=e.getTime()){u=h;r=true}}if(h.oname!="")l=gettext("Organized by")+" "+h.oname;p=m==1?interpolate(ngettext("%(number_events)s event has been found for the same date","%(number_events)s events have been found for the same date",h.date),{number_events:gTabNbrEventDate[idxTabEventdate]},true):h.name+" "+l;document.getElementById(valueDay).innerHTML='<a href="javascript:selDateEvent('+i+",'"+currentDayMonth+"',"+m+",'"+c+"','"+valueDay+"',"+showPrivateEvents+
",'"+h.sig+'\') ;" title="'+p+'" >'+f+"</a>";q[currentDayMonth]=h;if(o[i]!="*"){o[i]="*";s.push(i);v.push(currentDayMonth);w.push(m)}k+=parseInt(gTabNbrEventDate[idxTabEventdate]);d+=1}else document.getElementById(valueDay).innerHTML=f}}else document.getElementById(valueDay).innerHTML=f}else{for(b=j;b<42;b++){valueDay="day_"+b;document.getElementById(valueDay).style.display="none"}break}}document.getElementById("currentMonth").title=interpolate(ngettext("%(number_events)s Event found on %(month)s",
"%(number_events)s Events found on %(month)s",k),{number_events:k,month:monthNames[a-1]},true);if(s.length>0){displayElement("event_window_register","block");a={};a=selectedEventDate in q?q[selectedEventDate]:r?u:t;selDateEvent(a.eid,a.date,a.multiEvent,c,"",showPrivateEvents,a.sig)}else{displayElement("event_window_register","none");displayElement("ebcalmultipledates","none")}if(document.getElementById("rightcol"))document.getElementById("rightcol").style.display="block";return d}
function displayElement(a,b){var c=document.getElementById(a);if(c)c.style.display=b}function searchForOrganizer(a,b){for(var c=0;c<gTabEventDate.length;c++)if(gTabEventDate[c]==b&&gTabEventDateOrg[c]==a)return c+1;return 0}
function computeMinmaxEventDate(a){var b="",c="";c=[];b=0;if(a){for(var d in gTabEventReference)if(gTabEventOrganizerIdReference[d]==a){b+=1;if(gTabEventDateListReference[d]=="")c.push(gTabEventDateReference[d]);else c=c.concat(gTabEventDateListReference[d].split(","))}if(b>0){b=new Date(c.min());gMinEventDate=b.getFullYear()+"/"+PadDigits(b.getMonth()+1,2);c=new Date(c.max());gMaxEventDate=c.getFullYear()+"/"+PadDigits(c.getMonth()+1,2);return b}}else{b=new Date(gTabEventDate.min());gMinEventDate=
b.getFullYear()+"/"+PadDigits(b.getMonth()+1,2);c=new Date(gTabEventDate.max());gMaxEventDate=c.getFullYear()+"/"+PadDigits(c.getMonth()+1,2);return b}}
function calendarType(a,b){var c=0;if(a=="ALL"||a==""){gSelectCalendarType="ALL";gFilterByOrganizer="";if(document.getElementById("all_my_events"))document.getElementById("all_my_events").checked="checked";gDateEvent=computeMinmaxEventDate();c=initCalendar(gCurrentMonth,gCurrentYear,gFilterByOrganizer);gTotalFoundLiveEvent>0&&checkNextValidMonth(c)}else{gSelectCalendarType="ORG";gFilterByOrganizer=gSelectCurrentOrganizer;if(document.getElementById("by_organizer"))document.getElementById("by_organizer").checked=
"checked";if(gDateEvent=computeMinmaxEventDate(gFilterByOrganizer)){c=initCalendar(gCurrentMonth,gCurrentYear,gFilterByOrganizer);gTotalFoundLiveEvent>0&&checkNextValidMonth(c)}else gTotalFoundLiveEvent==0&&initCalendar(gCurrentMonth,gCurrentYear,gFilterByOrganizer)}if(currentWidget=="CALENDAR")document.getElementById("widget_calendar_type").value=gSelectCalendarType;updateCalendarNavigation(gCurrentCalendarDate);if(!b)document.getElementById("iframeCode").value=""}
function checkNextValidMonth(a){if(a==0){a=changeMonth("NEXT","check");if(a==0){gCurrentYear=gDateEvent.getFullYear();gCurrentMonth=gDateEvent.getMonth()+1;initCalendar(gCurrentMonth,gCurrentYear,gFilterByOrganizer);gCurrentCalendarDate=new Date(formatCalDate(gCurrentYear,gCurrentMonth,"long"));updateCalendarNavigation(gCurrentCalendarDate)}}}
function changeMonth(a,b){var c=0,d=1,e=formatCalDate(gCurrentYear,gCurrentMonth);if(a=="PREV")d=-1;for(;e<=gMaxEventDate&&e>=gMinEventDate;){c=addMonth(new Date(formatCalDate(gCurrentYear,gCurrentMonth,"long")),d);gCurrentYear=c.getFullYear();gCurrentMonth=c.getMonth()+1;e=formatCalDate(gCurrentYear,gCurrentMonth);c=initCalendar(gCurrentMonth,gCurrentYear,gFilterByOrganizer);if(c>0){gLastMonth=gCurrentMonth;gLastYear=gCurrentYear;gCurrentCalendarDate=new Date(formatCalDate(gCurrentYear,gCurrentMonth,
"long"));updateCalendarNavigation(gCurrentCalendarDate);break}else if(e>gMaxEventDate||e<gMinEventDate){gCurrentMonth=gLastMonth;gCurrentYear=gLastYear;gCurrentCalendarDate=new Date(formatCalDate(gCurrentYear,gCurrentMonth,"long"));c=initCalendar(gCurrentMonth,gCurrentYear,gFilterByOrganizer);updateCalendarNavigation(gCurrentCalendarDate);break}}if(b)return c}function formatCalDate(a,b,c){var d="";if(c)d="/01";return a+"/"+PadDigits(b,2)+d}
function updateCalendarNavigation(a){a=formatCalDate(a.getFullYear(),a.getMonth()+1);document.getElementById("PREV_button").innerHTML="&lt;";document.getElementById("NEXT_button").innerHTML="&gt;";document.getElementById("NEXT_button").href="javascript: changeMonth('NEXT');";document.getElementById("PREV_button").href="javascript: changeMonth('PREV');";document.getElementById("NEXT_button").style.backgroundColor=userThinOutlineColor;document.getElementById("PREV_button").style.backgroundColor=userThinOutlineColor;
if(a>=gMaxEventDate||gTotalFoundLiveEvent==0){document.getElementById("NEXT_button").innerHTML="";document.getElementById("NEXT_button").href="javascript:void(0);";document.getElementById("NEXT_button").style.backgroundColor=userBackgroundColor}if(a<=gMinEventDate||gTotalFoundLiveEvent==0){document.getElementById("PREV_button").innerHTML="";document.getElementById("PREV_button").href="javascript:void(0);";document.getElementById("PREV_button").style.backgroundColor=userBackgroundColor}}
function addMonth(a,b){var c=new Date(a),d=c.getMonth()+1;c=c.getFullYear();d+=b;if(d<=0){d=12-(b+1);c-=1}else if(d>12){d-=12;c+=1}return new Date(c+"/"+d+"/01")}function createWidget(){gClickOnCreateWidget=1;document.getElementById("submitted").value="1";document.widgetForm.target="_top";document.widgetForm.submit()}
function clsEventData(a){document.getElementById("display_eventname").style.display=a;document.getElementById("display_eventdate").style.display=a;document.getElementById("display_eventvenue").style.display=a;document.getElementById("display_eventlocation").style.display=a;document.getElementById("display_eventtweeter").style.display=a}
function selDateEvent(a,b,c,d,e,g,j){if(gLastDisplayEvent!=a||gLastDisplayDateEvent!=b||gLastDisplayOrg!=d||gLastDisplayListedType!=g){var f="";gLastCalendarDivSelected=e;if(c==1)f="&multevent=1";if(g){f+="&showPrivate=1";f+="&sig="+j}if(d!="")f+="&org="+d;c="eid="+encodeURIComponent(a)+"&date="+encodeURIComponent(b)+f;jQuery.ajax({url:"/eventcalendar",type:"POST",data:c,success:function(k,l,o){displayCalendarEvent(o)},error:noEventData});gLastDisplayEvent=a;gLastDisplayDateEvent=b;gLastDisplayOrg=
d;gLastDisplayListedType=g}}
function saveWidgetSettings(a,b){var c="eid="+encodeURIComponent(a);c+="&widget="+encodeURIComponent(b);switch(b){case "CALENDAR":case "COUNTDOWN":c+="&widget_calendar_type="+encodeURIComponent(gSelectCalendarType);c+="&widget_text_color="+encodeURIComponent(userMessageColor);c+="&widget_background_color="+encodeURIComponent(userBackgroundColor);c+="&widget_thin_outline="+encodeURIComponent(userThinOutlineColor);c+="&widget_thick_outline="+encodeURIComponent(userThickOutlineColor);c+="&widget_text_other_color="+
encodeURIComponent(userTextColor);for(var d in gSelectComponent)c+="&post_"+d+"="+gSelectComponent[d];previousUserMessageColor=userMessageColor;previousUserBackgroundColor=userBackgroundColor;previousUserThinOutlineColor=userThinOutlineColor;previousUserThickOutlineColor=userThickOutlineColor;previousUserTextColor=userTextColor;for(d in gSelectComponent)gOriginalSelectComponent[d]=gSelectComponent[d];break;case "BUTTON":c+=EB.ButtonWidget.saveWidgetParams()}jQuery.ajax({url:"/widgetsettings",type:"POST",
data:c,success:widgetSaved,error:noEventData})}function widgetSaved(){document.getElementById("embedpanel").scrollIntoView(true)}
function displayCalendarEvent(a){if(a.responseText)if(objEvent=JSON.parse(a.responseText)){gNbrEventByDate=1;gEventName=objEvent.name;gSelectCurrentEID=objEvent.eid;gEventLogo=objEvent.logo;gEventName=objEvent.name;gEventVenue=objEvent.venue;gEventDates=objEvent.date;gEventShortDates=objEvent.dateshort;gEventAddress=objEvent.address;gEventUrl=objEvent.regurl;gTwitterUrl=objEvent.twitter;gLocationMapUrl=objEvent.mapurl;if(parseInt(objEvent.nbrevent)>1){gNbrEventByDate=objEvent.nbrevent;gArrayEID=objEvent.listeid;
gArrayEventName=objEvent.listname;gArrayEventTime=objEvent.listtime;gArrayEventOrganizer=objEvent.listorg;gArrayEventLocation=objEvent.location}affectEbCalendar()}}function noEventData(){alert("No Event Found");return false}
function affectEbCalendar(){for(var a=0;a<gMaxEventPerDay;a++){valueDay="event_"+a;document.getElementById(valueDay).innerHTML="";document.getElementById(valueDay).style.display="none"}document.getElementById("event_window_register").style.display="block";document.getElementById("ebcalmultipledates").style.display="none";if(gLastCalendarDivSelected!="")document.getElementById(gLastCalendarDivSelected).title="";if(gNbrEventByDate>1){if(gLastCalendarDivSelected!="")document.getElementById(gLastCalendarDivSelected).title=
interpolate(ngettext("%(number_events)s event has been found for the same date","%(number_events)s events have been found for the same date",gNbrEventByDate),{number_events:gNbrEventByDate},true);document.getElementById("event_window_register").style.display="none";document.getElementById("ebcalmultipledates").style.display="block";document.getElementById("mult_event_title").innerHTML=gettext("Events on ")+gEventShortDates;if(gNbrEventByDate>gMaxEventPerDay)gNbrEventByDate=gMaxEventPerDay;for(a=0;a<
gNbrEventByDate;a++){orgTitle="";if(gArrayEventOrganizer[a]!="")orgTitle=" "+gettext("Organized By")+" "+gArrayEventOrganizer[a];valueDay="event_"+a;EventUrl='<a href="'+baseUrl+"/event/"+gArrayEID[a]+'?ref=ecal" target="_blank" class="active" title="'+gArrayEventName[a]+orgTitle+'" >';EventUrl+="<span>"+gettext("Register now for:")+"</span><br />"+gArrayEventName[a]+"<br />";EventUrl+="<span>"+gArrayEventTime[a];if(gArrayEventLocation[a]!=""&&gArrayEventLocation[a]!=" ")EventUrl+=" / "+gArrayEventLocation[a];
EventUrl+="</span>";document.getElementById(valueDay).innerHTML=EventUrl;document.getElementById(valueDay).style.display="block"}}eventLogo=gSelectComponent.eventlogo==1?gEventLogo!=""&&gEventLogo!=null?'<a href="'+gEventUrl+'" id="display_eventlogo" target="_blank" ><img src="'+gEventLogo+'" width="173" /></a>':"":"";document.getElementById("display_eventdate").innerHTML=gEventDates;document.getElementById("display_eventregister").href=gEventUrl;document.getElementById("display_eventlocation").href=
gLocationMapUrl;document.getElementById("display_eventvenue").href=gLocationMapUrl;document.getElementById("display_eventname").href=gEventUrl;document.getElementById("display_eventlogo").innerHTML=eventLogo;document.getElementById("display_eventname").innerHTML=gEventName;document.getElementById("display_eventlocation").innerHTML=gEventAddress;document.getElementById("display_eventvenue").innerHTML=gEventVenue;document.getElementById("display_eventtweeter").href=gTwitterUrl}
function getRandomFooterLink(a,b){var c="eid="+encodeURIComponent(a)+"&widget="+b;jQuery.ajax({url:"/widget-footer-link",type:"POST",data:c,success:function(d,e,g){displayFooterLink(g)},error:noEventData})}function displayFooterLink(a){if(a.responseText)if(objFooter=JSON.parse(a.responseText))if(objFooter.status=="ok"){gWidgetFooterLink=objFooter.footer;document.getElementById("frt"+objFooter.eid).innerHTML=gWidgetFooterLink;embeddedCode()}}
function CopyToClipboard(){document.getElementById("iframeCode").focus();document.getElementById("iframeCode").select();CopiedTxt=document.selection.createRange();CopiedTxt.execCommand("Copy");alert(gettext("The code was copied to your clipboard."))}function copyZeroClipBoard(){clip.setText(document.getElementById("iframeCode").value)}function completeCopyClip(){alert(gettext("The code was copied to your clipboard."))}function loadCopyClip(){};var gNbrEventDigits=4,gColorFooter="#ddd",gFrtDiv="div9999",gFrameID="frameId9999",gFooterDiv="frt9999",gframeDivId="frm9999",gFooterUrlDiv="ftu9999",gFooterUrlSpan="spa9999",gFooterUrlSpan2="spac9999",gSpanFooter="spuc9999",gSpanFooter2="spud9999";function regFrm(a,b,c){if(!c){c=gup(a.src,"eid");c=c.substring(c.length,gNbrEventDigits+1)}var d=getWidgetCode(a.src);formatDivId(c);adjustHeight=mainCustomIframe(d,a);customIframeFooter();a.style.height=b+adjustHeight+"px"}
function formatDivId(a){gFrameID="frameId"+a;gFooterDiv="ftr"+a;gFrameID="frameId"+a;gMainFrameDiv="div"+a;gFooterUrlDiv="ftu"+a;gFooterUrlSpan="spac"+a;gFooterUrlSpan2="spuc"+a;gSpanFooter="spa"+a;gSpanFooter2="spu"+a}
function customIframeFooter(){if(document.getElementById(gFooterDiv)){var a=document.getElementById(gFooterDiv);a.style.fontFamily="Helvetica, Arial";a.style.fontSize="10px";a.style.padding="5px 0 5px";a.style.margin="2px"}if(document.getElementById(gFooterUrlDiv)){a=document.getElementById(gFooterUrlDiv);a.style.color=gColorFooter;a.style.textDecoration="none";a.target="_blank"}if(document.getElementById(gFooterUrlSpan)){a=document.getElementById(gFooterUrlSpan);a.style.color=gColorFooter;a.style.textDecoration=
"none";a.target="_blank"}if(document.getElementById(gFooterUrlSpan2)){a=document.getElementById(gFooterUrlSpan2);a.style.color=gColorFooter;a.style.textDecoration="none";a.target="_blank"}if(document.getElementById(gSpanFooter)){a=document.getElementById(gSpanFooter);a.style.color=gColorFooter}if(document.getElementById(gSpanFooter2)){a=document.getElementById(gSpanFooter2);a.style.color=gColorFooter}}
function mainCustomIframe(a,b){b.style.visibility="visible";var c=0;switch(a){case "ecal":c=adaptHeightByBrowser("ecal");b.width="220";b.marginheight="0";b.marginwidth="0";b.frameBorder="no";b.scrolling="no";if(document.getElementById(gMainFrameDiv)){var d=document.getElementById(gMainFrameDiv);d.style.width="195px";d.style.textAlign="center"}if(document.getElementById(gFooterDiv)){d=document.getElementById(gFooterDiv);d.style.width="195px";d.style.textAlign="center";d.style.margin="2px"}break;case "ecount":c=
adaptHeightByBrowser("ecount");b.width="220";b.marginheight="0";b.marginwidth="0";b.frameBorder="no";b.scrolling="no";if(document.getElementById(gMainFrameDiv)){d=document.getElementById(gMainFrameDiv);d.style.width="195px";d.style.textAlign="center"}if(document.getElementById(gFooterDiv)){d=document.getElementById(gFooterDiv);d.style.width="195px";d.style.textAlign="center";d.style.margin="2px"}break;case "widget":case "etckt":c=adaptHeightByBrowser("etckt");b.width="100%";b.marginheight="5";b.marginwidth=
"5";b.vspace="0";b.hspace="0";b.scrolling="auto";b.allowtransparency="true";if(document.getElementById(gMainFrameDiv)){d=document.getElementById(gMainFrameDiv);d.style.width="100%";d.style.textAlign="left"}if(document.getElementById(gFooterDiv)){d=document.getElementById(gFooterDiv);d.style.width="100%";d.style.textAlign="left"}break;case "eweb":c=adaptHeightByBrowser("eweb");b.width="100%";b.marginheight="5";b.marginwidth="5";b.vspace="0";b.hspace="0";b.scrolling="auto";b.allowtransparency="true";
if(document.getElementById(gMainFrameDiv)){d=document.getElementById(gMainFrameDiv);d.style.width="100%";d.style.textAlign="left"}if(document.getElementById(gFooterDiv)){d=document.getElementById(gFooterDiv);d.style.width="100%";d.style.textAlign="left"}}return c}function gup(a,b){b=b.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var c=RegExp("[\\?&]"+b+"=([^&#]*)").exec(a);return c==null?"":c[1]}
function getWidgetCode(a){return a.indexOf("/calendar")>=0?"ecal":a.indexOf("/countdown")>=0?"ecount":a.indexOf("/event")>=0?"eweb":a.indexOf("/tickets")>=0?"etckt":"widget"}
function adaptHeightByBrowser(a){var b=navigator.appVersion,c=navigator.appName,d=navigator.platform;if(b.indexOf("Mac")>=0||b.indexOf("Safari")>=0)switch(a){case "ecal":return 25;case "etckt":return 10;case "ecount":return 25;case "eweb":return 10}if(c.indexOf("Netscape")>=0&&d.indexOf("Win32")>=0)switch(a){case "ecal":return 20;case "etckt":return 25;case "ecount":return 10;case "eweb":return 10}if(b.indexOf("MSIE")>=0&&d.indexOf("Win32")>=0)switch(a){case "ecal":return 65;case "etckt":return 30;
case "ecount":return 50;case "eweb":return 40}return 20};
