window.EB=window.EB||{};EB.EventUtil=function(){return{addHandler:function(c,d,e){c.addEventListener?c.addEventListener(d,e,!1):c.attachEvent?c.attachEvent("on"+d,e):c["on"+d]=e},removeHandler:function(c,d,e){c.removeEventListener?c.removeEventListener(d,e,!1):c.detachEvent?c.detachEvent("on"+d,e):c["on"+d]=null},getEvent:function(c){return c?c:window.event},getTarget:function(c){return c.target||c.srcElement}}}();this.JSON||(JSON=function(){function c(c){return 10>c?"0"+c:c}function d(c){g.lastIndex=0;return g.test(c)?'"'+c.replace(g,function(c){var d=k[c];return"string"===typeof d?d:"\\u"+("0000"+(+c.charCodeAt(0)).toString(16)).slice(-4)})+'"':'"'+c+'"'}function e(c,f){var g,p,k,q,r=m,n,h=f[c];h&&("object"===typeof h&&"function"===typeof h.toJSON)&&(h=h.toJSON(c));"function"===typeof l&&(h=l.call(f,c,h));switch(typeof h){case "string":return d(h);case "number":return isFinite(h)?String(h):"null";case "boolean":case "null":return String(h);
case "object":if(!h)return"null";m+=j;n=[];if("number"===typeof h.length&&!h.propertyIsEnumerable("length")){q=h.length;for(g=0;g<q;g+=1)n[g]=e(g,h)||"null";k=0===n.length?"[]":m?"[\n"+m+n.join(",\n"+m)+"\n"+r+"]":"["+n.join(",")+"]";m=r;return k}if(l&&"object"===typeof l){q=l.length;for(g=0;g<q;g+=1)p=l[g],"string"===typeof p&&(k=e(p,h))&&n.push(d(p)+(m?": ":":")+k)}else for(p in h)Object.hasOwnProperty.call(h,p)&&(k=e(p,h))&&n.push(d(p)+(m?": ":":")+k);k=0===n.length?"{}":m?"{\n"+m+n.join(",\n"+
m)+"\n"+r+"}":"{"+n.join(",")+"}";m=r;return k}}Date.prototype.toJSON=function(){return this.getUTCFullYear()+"-"+c(this.getUTCMonth()+1)+"-"+c(this.getUTCDate())+"T"+c(this.getUTCHours())+":"+c(this.getUTCMinutes())+":"+c(this.getUTCSeconds())+"Z"};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var f=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,g=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
m,j,k={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},l;return{stringify:function(c,d,f){var g;j=m="";if("number"===typeof f)for(g=0;g<f;g+=1)j+=" ";else"string"===typeof f&&(j=f);if((l=d)&&"function"!==typeof d&&("object"!==typeof d||"number"!==typeof d.length))throw Error("JSON.stringify");return e("",{"":c})},parse:function(c,d){function e(c,f){var g,j,h=c[f];if(h&&"object"===typeof h)for(g in h)Object.hasOwnProperty.call(h,g)&&(j=e(h,g),void 0!==j?h[g]=j:delete h[g]);
return d.call(c,f,h)}var g;f.lastIndex=0;f.test(c)&&(c=c.replace(f,function(c){return"\\u"+("0000"+(+c.charCodeAt(0)).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(c.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return g=eval("("+c+")"),"function"===typeof d?e({"":g},""):g;throw new SyntaxError("JSON.parse");}}}());var GLOBAL_LIMIT_DATE=2037,GLOBAL_DEFAULT_LIMIT_DATE="01/01/2037",GLOBAL_DISPLAY_CALENDAR=!1,GLOBAL_MODE_DATE="",GLOBAL_MAX_INTEGER=1E6,GLOBAL_MAX_QUANTITY=1E4,GLOBAL_RED="DC143C",GLOBAL_BLACK="000000",GLOBAL_DAY_SECOND=86400,GLOBAL_HOUR_SECOND=3600,GLOBAL_MN_SECOND=60,GLOBAL_ID_MESSAGE="",GLOBAL_ID_MESSAGE_SOURCE="",GLOBAL_TIMEOUT_MESSAGE=3E3,GLOBAL_API_KEY_UPPERCASE=!0,GLOBAL_API_KEY_LENGTH=16,GLOBAL_API_KEY_NUMBER=!0,gMonth_names_fr={},gMonth_names_us={},gMonth_days={"01":31,1:31,"02":28,2:28,
"03":31,3:31,"04":30,4:30,"05":31,5:31,"06":30,6:30,"07":31,7:31,"08":31,8:31,"09":30,9:30,10:31,11:30,12:31};gMonth_names_fr["01"]="Janvier";gMonth_names_fr["1"]="Janvier";gMonth_names_fr["02"]="F\u00e9vrier";gMonth_names_fr["2"]="F\u00e9vrier";gMonth_names_fr["03"]="Mars";gMonth_names_fr["3"]="Mars";gMonth_names_fr["04"]="Avril";gMonth_names_fr["4"]="Avril";gMonth_names_fr["05"]="Mai";gMonth_names_fr["5"]="Janvier";gMonth_names_fr["06"]="Juin";gMonth_names_fr["6"]="Juin";gMonth_names_fr["07"]="Juillet";
gMonth_names_fr["7"]="Janvier";gMonth_names_fr["08"]="Ao\u00fbt";gMonth_names_fr["8"]="Ao\u00fbt";gMonth_names_fr["09"]="Septembre";gMonth_names_fr["9"]="Septembre";gMonth_names_fr["10"]="Octobre";gMonth_names_fr["11"]="Novembre";gMonth_names_fr["12"]="D\u00e9cembre";gMonth_names_us["01"]="January";gMonth_names_us["1"]="January";gMonth_names_us["02"]="February";gMonth_names_us["2"]="February";gMonth_names_us["03"]="March";gMonth_names_us["3"]="March";gMonth_names_us["04"]="April";
gMonth_names_us["4"]="April";gMonth_names_us["05"]="May";gMonth_names_us["5"]="May";gMonth_names_us["06"]="June";gMonth_names_us["6"]="June";gMonth_names_us["07"]="July";gMonth_names_us["7"]="July";gMonth_names_us["08"]="August";gMonth_names_us["8"]="August";gMonth_names_us["09"]="September";gMonth_names_us["9"]="September";gMonth_names_us["10"]="October";gMonth_names_us["11"]="November";gMonth_names_us["12"]="December";function BisexYear(c,d){return 0==c%4&&2==d?!0:!1}
function nbDaysPerMonth(c,d){var e=gMonth_days[c];BisexYear(d,c)&&e++;return e}function getMonthName(c,d){switch(d){case "FR":return gMonth_names_fr[c];case "US":return gMonth_names_us[c]}}function PadDigits(c,d){c=c.toString();var e="";if(d>c.length)for(i=0;i<d-c.length;i++)e+="0";return e+c.toString()}function CountCar(c,d,e){return c.split(d).length-1>e?!0:!1}
function IsNumeric(c){var d,e=!0;if(0==c.length)return!1;for(i=0;i<c.length&&!0==e;i++)d=c.charAt(i),-1=="0123456789.-".indexOf(d)&&(e=!1);return e}function checkInteger(c){newVal=parseInt(c.value);isNaN(newVal)?(alert(gettext("Please enter an integer value.")),c.value=0,c.focus()):c.value=newVal;return!1}
function CheckNumeric(c,d,e,f,g,m){var j=document.getElementById(c).value,j=j.replace(",","");document.getElementById(c).value=j;var k=0;"F"==d?(reg=/[^0-9.]/i,k=1):reg=/[^0-9]/i;var k=CountCar(j,".",k),l=GLOBAL_MAX_INTEGER;e&&(l=e);!reg.test(j)&&!k?parseInt(j)>l&&0<l?(alert(gettext("Numbers must be less or equal to")+" "+l+"."),document.getElementById(c).value=l,document.getElementById(c).focus()):(document.getElementById(c).style.color="#"+GLOBAL_BLACK,3<=arguments.length&&f&&f(g)):(document.getElementById(c).style.color=
"#"+GLOBAL_RED,k&&"I"==d?alert(gettext("Please enter integer numbers here.")):alert(gettext("Please enter numbers here.")),document.getElementById(c).value=j.substring(0,j.length-1))}
function CheckNumeric_Localization(c,d,e,f,g,m){var j=document.getElementById(c).value,j=j.replace(",","");document.getElementById(c).value=j;var k=0;"F"==d?(reg=/[^0-9.]/i,k=1):reg=/[^0-9]/i;var k=CountCar(j,".",k),l=GLOBAL_MAX_INTEGER;e&&(l=e);!reg.test(j)&&!k?parseInt(j)>l&&0<l?(display_error_msg("alert","numericlength","register",l),document.getElementById(c).value=l,document.getElementById(c).focus()):(document.getElementById(c).style.color="#"+GLOBAL_BLACK,3<=arguments.length&&f&&f(g)):(document.getElementById(c).style.color=
"#"+GLOBAL_RED,k&&"I"==d?display_error_msg("alert","numericinteger","register"):display_error_msg("alert","numeric","register"),document.getElementById(c).value=j.substring(0,j.length-1))}function ShowCalendar(c,d){var e=["2000.01"];e[1]=GLOBAL_LIMIT_DATE+".01";GLOBAL_MODE_DATE=c;Date.parse(d)||(d=new Date);Calendar.setup({inputField:c,button:c,eventName:"click",ifFormat:"%m/%d/%Y",align:"Bl",range:e,date:new Date(d),cache:!0,electric:!1})}
function AddToCalendar(c,d,e,f){d=d+"/calendar.ics?eid="+e+"&calendar="+c;if(f)d+="&date="+f;else if(document.mgform&&document.mgform.selecteddate){if(1>document.mgform.selecteddate.selectedIndex){alert(gettext("Please select the date you would like to attend."));return}d+="&date="+document.mgform.selecteddate[document.mgform.selecteddate.selectedIndex].value}"outlook"==c||"ical"==c?document.location.href=d:window.open(d,"calendar","toolbar=yes, menubar=yes, location=yes, status=yes, scrollbars=yes,resizable=yes, width=800, height=600, left=0, top=0")}
function CheckLimitDate(c){var d=c.getFullYear();c=new Date(c);return d>GLOBAL_LIMIT_DATE?new Date(GLOBAL_DEFAULT_LIMIT_DATE):c}function Show(c,d){document.getElementById(c)&&"none"==document.getElementById(c).style.display&&("undefined"!=typeof d&&""!=d?document.getElementById(c).style.display=d:document.getElementById(c).style.display="block")}function Hide(c){document.getElementById(c)&&"none"!=document.getElementById(c).style.display&&(document.getElementById(c).style.display="none")}
function ShowInline(c){document.getElementById(c)&&"none"==document.getElementById(c).style.display&&(document.getElementById(c).style.display="inline")}function HideInline(c){document.getElementById(c)&&"none"!=document.getElementById(c).style.display&&(document.getElementById(c).style.display="none")}function Toggle(c){document.getElementById(c)&&("none"==document.getElementById(c).style.display?Show(c):Hide(c))}
function ToggleDiv(c,d){document.getElementById(c)&&("none"==document.getElementById(c).style.display?"undefined"!=typeof d&&""!=d?Show(c,d):Show(c):Hide(c))}function checkEmail(c){return window.RegExp?RegExp("^[0-9a-zA-Z]+([.-]?[0-9a-zA-Z#'+/^`~_-]+)*@[0-9a-zA-Z]+[0-9a-zA-Z.-]*[.]{1}(travel|museum|[a-zA-Z]{2,4})$").test(c)?!0:!1:0<=c.indexOf("@")?!0:!1}
function CheckEmailExtended(c){if(document.getElementById(c)){email=document.getElementById(c).value;if(!checkEmail(email))return alert(gettext("This is not a valid email address.")),document.getElementById(c).focus(),!1;AtPos=email.indexOf("@");StopPos=email.lastIndexOf(".");Message="";if(""==email||-1==AtPos||-1==StopPos||StopPos<AtPos||1==StopPos-AtPos)return alert(gettext("This is not a valid email address.")),document.getElementById(c).focus(),!1}return!0}
function saveEventUrl(){var c=jQuery("#eventshortname").attr("value");if(!CheckShortname(c)&&c)alert(gettext('Your "Personalized Event URL" can only include lowercase letters and numbers'));else{var d=server+"/seteventurl",c="shortname="+c+"&event_id="+jQuery("#event_id").attr("value");jQuery.ajax({url:d,data:c,success:updateEventShortname,error:throwFailure})}}
function saveOrgUrl(){var c=jQuery("#orgshortname").attr("value");if(!CheckShortname(c)&&c)alert(gettext('Your "Personalized Organizer URL" can only include lowercase letters and numbers.'));else{var d=server+"/setorganizerurl",c="shortname="+c+"&org_id="+jQuery("#org_id").attr("value");jQuery.ajax({url:d,data:c,success:updateOrgShortname,error:throwFailure})}}function throwFailure(c){alert(c.responseText)}
function updateOrgShortname(c){c=c?"http://"+c+"."+domain:server+"/org/"+oid;style&&(c+="?s="+style);jQuery("#organizer_url").html('<a href="'+c+'">'+c+"</a>");ToggleDiv("organizer_personalizedurl")}function updateEventShortname(c){c=c?"http://"+c+"."+domain:server+"/event/"+eid;jQuery("#event_url").html('<a href="'+c+'">'+c+"</a>");ToggleDiv("event_personalizedurl")}function CheckShortname(c){return""==c?!1:/[^a-z0-9-]/.test(c)?!1:!0}
function SetCookie(c,d,e){var f=new Date,g=new Date;if(null==e||0==e)e=1;g.setTime(f.getTime()+864E5*e);document.cookie=c+"="+encodeURIComponent(d)+";expires="+g.toGMTString()}function ReadCookie(c){var d=""+document.cookie,e=d.indexOf(c);if(-1==e||""==c)return"";var f=d.indexOf(";",e);-1==f&&(f=d.length);return unescape(d.substring(e+c.length+1,f))}function EraseCookie(c){SetCookie(c,"",-1)}function TestCookies(){SetCookie("test","1",1);return"1"==ReadCookie("test")?(EraseCookie("test"),!0):!1}
function ShowDiv(c){document.getElementById(c)&&"none"==document.getElementById(c).style.display&&(document.getElementById(c).style.display="block")}function HideDiv(c){document.getElementById(c)&&"none"!=document.getElementById(c).style.display&&(document.getElementById(c).style.display="none")}
function ShowDivFromCheckbox(c,d){c.checked?(Show(d),document.getElementById(d).focus()):("channelsDiv"==d&&($("channels").options[0].selected=!0,$("channels_2").options[0].selected=!0,$("tags").value=""),Hide(d))}function common_replace_car(c,d,e){var f=c;document.getElementById(c)&&(f=document.getElementById(c).value);c=d?d:'"';e=e?e:"'";f=f.split("");for(d=0;d<f.length;d++)wcar=f[d],wcar=wcar.replace(c,e),f[d]=wcar;return f=f.join("")}
function CopyText(c,d){var e=document.getElementById(c),f=document.getElementById(d);""!=e&&""!=f&&(f.value=e.value)}function ControlDate(c){c=document.getElementById(c);alert(c)}function ValidCheckBox(c){if(document.getElementById(c)){c=document.getElementById(c);var d=c.length,e="";for(i=0;i<d;i++)c[i].checked&&(e=e+c[i].value+" ");return""==e?(Alert("No boxes checked."),!1):!0}}function cGA(c){"undefined"!=typeof pageTracker&&pageTracker._trackPageview(c)}
function isInt(c){return 0==c.toString().search(/^-?[0-9]+$/)}var STR_PAD_LEFT=1,STR_PAD_RIGHT=2,STR_PAD_BOTH=3;function paddingSTR(c,d,e,f){"undefined"==typeof d&&(d=0);"undefined"==typeof e&&(e=" ");"undefined"==typeof f&&(f=STR_PAD_RIGHT);if(d+1>=c.length)switch(f){case STR_PAD_LEFT:c=Array(d+1-c.length).join(e)+c;break;case STR_PAD_BOTH:d=Math.ceil((padlen=d-c.length)/2);c=Array(padlen-d+1).join(e)+c+Array(d+1).join(e);break;default:c+=Array(d+1-c.length).join(e)}return c}
String.prototype.trim=function(){return this.replace(/^\s+/,"").replace(/\s+$/,"")};function checkHTML(c){var d=e,e=document.getElementById(c).value;try{d=HTMLtoXML(e),254<d.length&&(d=e)}catch(f){d=e}document.getElementById(c).value=d;return!0}function splitTrim(c,d){if(0<=c.indexOf(d)){for(var e=c.split(d),f=0;f<e.length;f++)e[f]=e[f].trim();c=e.join(d)}return c}function UpperName(c){return c.charAt(0).toUpperCase()+c.substring(1).toLowerCase()}
function Capitalize(c,d){var e=[];if(0<=c.indexOf(d)){var f=c.split(d);for(i=0;i<f.length;i++)e.push(UpperName(f[i]));return e.join(d)}return c}function extendedCapitalize(c){upperZone=c.trim();-1==upperZone.indexOf(",")&&(upperZone=0<=upperZone.indexOf(" ")?Capitalize(upperZone," "):0<=upperZone.indexOf("-")?Capitalize(upperZone,"-"):UpperName(upperZone));return upperZone}function stripHTML(c){return c.replace(/<&#91;^>&#93;*>/g,"")}
function limiteTextarea(c,d){if(c.value.length<d){a=c.value.split("\n");for(x=b=0;x<a.length;x++)a[x].length>=c.cols&&(b+=Math.floor(a[x].length/c.cols));b+=a.length;c.rows=b}else document.getElementById(c.name).value=c.value.substring(0,d)}
function BuildDateJS(c,d,e,f){if(document.getElementById(c))return c=document.getElementById(c).value,f=document.getElementById(f).value,d=document.getElementById(d).value,e=document.getElementById(e).value,"PM"==f?(f=parseInt(d,10),12>f&&(f+=12),d=f):(f=parseInt(d,10),12==f&&(d=0)),new Date(c+(" "+d+":"+e+":00"))}
function ComputeNewDate(c,d,e,f,g){""==e&&(e="0");""==f&&(f="0");""==g&&(g="0");e=parseInt(e);f=parseInt(f);g=parseInt(g);g=1E3*(e*GLOBAL_DAY_SECOND+f*GLOBAL_HOUR_SECOND+g*GLOBAL_MN_SECOND);d=new Date(d);""==c||"SUB"==c?d.setTime(d.getTime()-g):d.setTime(d.getTime()+g);e=d.getHours();g=d.getMinutes();c="AM";e=parseInt(e);g=parseInt(g);12<e&&(e-=12,c="PM");return{date:d.format("MM/DD/YYYY"),hour:PadDigits(e,2),minute:PadDigits(g,2),ampm:c}}
String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")};function unescapeHTMLFixed(c){newVal=new String(c);c=document.createElement("div");c.innerHTML=newVal.replace(/<\/?[^>]+>/gi,"");if(1>c.childNodes.length)return"";newVal=c.childNodes[0].nodeValue;newVal=newVal.replace(/&quot;/gi,'"');return newVal=newVal.replace(/&#39;/gi,"'")}
function isValidURL(c){return/^(([\w]+:)?\/\/)?(([\d\w]|%[a-fA-f\d]{2,2})+(:([\d\w]|%[a-fA-f\d]{2,2})+)?@)?([\d\w][-\d\w]{0,253}[\d\w]\.)+[\w]{2,4}(:[\d]+)?(\/([-+_~.\d\w]|%[a-fA-f\d]{2,2})*)*(\?(&?([-+_~.\d\w]|%[a-fA-f\d]{2,2})=?)*)?(#([-+_~.\d\w]|%[a-fA-f\d]{2,2})*)?$/.test(c)?!0:!1};
