var ZeroClipboard={version:"1.0.7",clients:{},moviePath:"ZeroClipboard.swf",nextId:1,$:function(a){"string"==typeof a&&(a=document.getElementById(a));a.addClass||(a.hide=function(){this.style.display="none"},a.show=function(){this.style.display=""},a.addClass=function(a){this.removeClass(a);this.className+=" "+a},a.removeClass=function(a){for(var c=this.className.split(/\s+/),d=-1,e=0;e<c.length;e++)c[e]==a&&(d=e,e=c.length);-1<d&&(c.splice(d,1),this.className=c.join(" "));return this},a.hasClass=
function(a){return!!this.className.match(RegExp("\\s*"+a+"\\s*"))});return a},setMoviePath:function(a){this.moviePath=a},dispatch:function(a,b,c){(a=this.clients[a])&&a.receiveEvent(b,c)},register:function(a,b){this.clients[a]=b},getDOMObjectPosition:function(a,b){for(var c={left:0,top:0,width:a.width?a.width:a.offsetWidth,height:a.height?a.height:a.offsetHeight};a&&a!=b;)c.left+=a.offsetLeft,c.top+=a.offsetTop,a=a.offsetParent;return c},Client:function(a){this.handlers={};this.id=ZeroClipboard.nextId++;
this.movieId="ZeroClipboardMovie_"+this.id;ZeroClipboard.register(this.id,this);a&&this.glue(a)}};
ZeroClipboard.Client.prototype={id:0,ready:!1,movie:null,clipText:"",handCursorEnabled:!0,cssEffects:!0,handlers:null,glue:function(a,b,c){this.domElement=ZeroClipboard.$(a);a=99;this.domElement.style.zIndex&&(a=parseInt(this.domElement.style.zIndex,10)+1);"string"==typeof b?b=ZeroClipboard.$(b):"undefined"==typeof b&&(b=document.getElementsByTagName("body")[0]);var d=ZeroClipboard.getDOMObjectPosition(this.domElement,b);this.div=document.createElement("div");var e=this.div.style;e.position="absolute";
e.left=""+d.left+"px";e.top=""+d.top+"px";e.width=""+d.width+"px";e.height=""+d.height+"px";e.zIndex=a;if("object"==typeof c)for(addedStyle in c)e[addedStyle]=c[addedStyle];b.appendChild(this.div);this.div.innerHTML=this.getHTML(d.width,d.height)},getHTML:function(a,b){var c="",d="id="+this.id+"&width="+a+"&height="+b;if(navigator.userAgent.match(/MSIE/))var e=location.href.match(/^https/i)?"https://":"http://",c=c+('<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="'+e+'download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0" width="'+
a+'" height="'+b+'" id="'+this.movieId+'" align="middle"><param name="allowScriptAccess" value="always" /><param name="allowFullScreen" value="false" /><param name="movie" value="'+ZeroClipboard.moviePath+'" /><param name="loop" value="false" /><param name="menu" value="false" /><param name="quality" value="best" /><param name="bgcolor" value="#ffffff" /><param name="flashvars" value="'+d+'"/><param name="wmode" value="transparent"/></object>');else c+='<embed id="'+this.movieId+'" src="'+ZeroClipboard.moviePath+
'" loop="false" menu="false" quality="best" bgcolor="#ffffff" width="'+a+'" height="'+b+'" name="'+this.movieId+'" align="middle" allowScriptAccess="always" allowFullScreen="false" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" flashvars="'+d+'" wmode="transparent" />';return c},hide:function(){this.div&&(this.div.style.left="-2000px")},show:function(){this.reposition()},destroy:function(){if(this.domElement&&this.div){this.hide();this.div.innerHTML=
"";var a=document.getElementsByTagName("body")[0];try{a.removeChild(this.div)}catch(b){}this.div=this.domElement=null}},reposition:function(a){a&&((this.domElement=ZeroClipboard.$(a))||this.hide());if(this.domElement&&this.div){a=ZeroClipboard.getDOMObjectPosition(this.domElement);var b=this.div.style;b.left=""+a.left+"px";b.top=""+a.top+"px"}},setText:function(a){this.clipText=a;this.ready&&this.movie.setText(a)},addEventListener:function(a,b){a=a.toString().toLowerCase().replace(/^on/,"");this.handlers[a]||
(this.handlers[a]=[]);this.handlers[a].push(b)},setHandCursor:function(a){this.handCursorEnabled=a;this.ready&&this.movie.setHandCursor(a)},setCSSEffects:function(a){this.cssEffects=!!a},receiveEvent:function(a,b){a=a.toString().toLowerCase().replace(/^on/,"");switch(a){case "load":this.movie=document.getElementById(this.movieId);if(!this.movie){var c=this;setTimeout(function(){c.receiveEvent("load",null)},1);return}if(!this.ready&&navigator.userAgent.match(/Firefox/)&&navigator.userAgent.match(/Windows/)){c=
this;setTimeout(function(){c.receiveEvent("load",null)},100);this.ready=!0;return}this.ready=!0;this.movie.setText(this.clipText);this.movie.setHandCursor(this.handCursorEnabled);break;case "mouseover":this.domElement&&this.cssEffects&&(this.domElement.addClass("hover"),this.recoverActive&&this.domElement.addClass("active"));break;case "mouseout":this.domElement&&this.cssEffects&&(this.recoverActive=!1,this.domElement.hasClass("active")&&(this.domElement.removeClass("active"),this.recoverActive=!0),
this.domElement.removeClass("hover"));break;case "mousedown":this.domElement&&this.cssEffects&&this.domElement.addClass("active");break;case "mouseup":this.domElement&&this.cssEffects&&(this.domElement.removeClass("active"),this.recoverActive=!1)}if(this.handlers[a])for(var d=0,e=this.handlers[a].length;d<e;d++){var g=this.handlers[a][d];if("function"==typeof g)g(this,b);else if("object"==typeof g&&2==g.length)g[0][g[1]](this,b);else if("string"==typeof g)window[g](this,b)}}};Array.prototype.max=function(){for(var a=this[0],b=this.length,c=1;c<b;c++)this[c]>a&&(a=this[c]);return a};Array.prototype.min=function(){for(var a=this[0],b=this.length,c=1;c<b;c++)this[c]<a&&(a=this[c]);return a};Array.prototype.in_array=function(a){for(var b in this)if(this[b]==a)return b;return 0};var ie=-1!=navigator.userAgent.indexOf("MSIE"),ie6=-1!=navigator.userAgent.indexOf("MSIE 6.0"),defaultFieldMessages={},gMinEventDate,gMaxEventDate;defaultFieldMessages.eventName=gettext("Attend This Event");
if("CALENDAR"==currentWidget||"CALENDAR-IFRAME"==currentWidget)gDateEvent=computeMinmaxEventDate();function fixForIE6(){if(ie6&&("COUNTDOWN"==currentWidget||"COUNTDOWN-IFRAME"==currentWidget))document.getElementById("highlight").className="highlight_IE6"}function checkKeyPress(a){if(window.event)a=window.event.keyCode;else if(a)a=a.which;else return!0;return 13==a?(saveWidgetSettings(gSelectCurrentEID,currentWidget),!1):!0}function resetIframe(){document.getElementById("iframeCode").value=""}
function dec2hex(a){a=a.toString(16).toUpperCase();return 1==a.length?"0"+a:a}function hex2dec(a){return parseInt(a,16)}function FieldtoHEX(a){a=document.getElementById(a);if(0>a.style.background.indexOf("rgb"))return a.style.background.toUpperCase();rgb=a.style.background.replace(/ /g,"");rgb=rgb.substring(rgb.indexOf("(")+1,rgb.indexOf(")"));rgb=rgb.split(",");return"#"+dec2hex(parseInt(rgb[0]))+dec2hex(parseInt(rgb[1]))+dec2hex(parseInt(rgb[2]))}
function openPicker(a){document.getElementById("iframeCode").value="";YAHOO.example.colorpicker.inDialog.setBoxID(a);a=document.getElementById(a);0<=a.style.background.indexOf("#")?rgb=YAHOO.util.Color.hex2rgb(a.style.background.substring(1,7)):(rgb=a.style.background.replace(/ /g,""),rgb=rgb.substring(rgb.indexOf("(")+1,rgb.indexOf(")")),rgb=rgb.split(","));document.getElementById("yui-picker-panel").style.display="block";YAHOO.example.colorpicker.inDialog.dialog.render();YAHOO.example.colorpicker.inDialog.getPicker().setValue([parseInt(rgb[0]),
parseInt(rgb[1]),parseInt(rgb[2])],!1);YAHOO.example.colorpicker.inDialog.dialog.show()}function affectBackgroundColor(a,b){var c=YAHOO.util.Color.hex2rgb(a.replace("#","")),c="rgb("+c[0]+", "+c[1]+", "+c[2]+")";b&&(document.getElementById(b).style.background=c);return c}
function initPicker(){var a,b="";YAHOO.example.colorpicker.inDialog={init:function(){this.dialog=new YAHOO.widget.Dialog("yui-picker-panel",{width:"400px",close:!0,fixedcenter:!0,modal:!0,visible:!1,constraintoviewport:!0,buttons:[{text:gettext("Cancel"),handler:this.handleCancel},{text:gettext("Save"),handler:this.handleSubmit,isDefault:!0}]});this.dialog.renderEvent.subscribe(function(){a||(a=new YAHOO.widget.ColorPicker("yui-picker",{container:this.dialog,showcontrols:!0,showhexcontrols:!0,showhsvcontrols:!1,
showwebsafe:!1,images:{PICKER_THUMB:"http://developer.yahoo.com/yui/examples/colorpicker/assets/picker_thumb.png",HUE_THUMB:"http://developer.yahoo.com/yui/examples/colorpicker/assets/hue_thumb.png"}}))})},getPicker:function(){return a},getBoxID:function(){return b},setBoxID:function(a){b=a},handleSubmit:function(){hex=a.getElement("yui-picker-hex").value;validHex=/(^(#)?[0-9A-F]{6}$)/i;if(!validHex.test(hex))return alert(gettext("Please enter a 6-digit hex color value.")),!1;rgbColor=affectBackgroundColor(hex,
b);"choose_text_color"==b&&(document.getElementById("choose_text_color").style.color=rgbColor,userMessageColor="#"+hex,"BUTTON"===currentWidget&&EB.ButtonWidget.updateColor("textColor",userMessageColor));"choose_text_other_color"==b?(document.getElementById("choose_text_other_color").style.color=rgbColor,userTextColor="#"+hex):"choose_background_color"==b?(document.getElementById("choose_background_color").style.color=rgbColor,userBackgroundColor="#"+hex,"BUTTON"===currentWidget&&EB.ButtonWidget.updateColor("backgroundColor",
userBackgroundColor)):"choose_thin_color"==b?(document.getElementById("choose_thin_color").style.color=rgbColor,userThinOutlineColor="#"+hex):"choose_thick_color"==b&&(document.getElementById("choose_thick_color").style.color=rgbColor,userThickOutlineColor="#"+hex);updateWidgetColor();this.cancel()},handleCancel:function(){this.cancel()}};YAHOO.util.Event.onDOMReady(YAHOO.example.colorpicker.inDialog.init,YAHOO.example.colorpicker.inDialog,!0)}
function checkSettingsUpdate(a){var b=0;switch(a){case "CALENDAR":b=checkColorUpdate(a);0==b&&(b=checkCountDownSelect(a));break;case "COUNTDOWN":b=checkColorUpdate(a);0==b&&(b=checkCountDownSelect(a));break;case "BUTTON":b=checkColorUpdate(a)}1==b&&0==gClickOnCreateWidget&&confirm(gettext("You have not saved changes to your Widget, press Ok to save"))&&embeddedCode()}
function checkCountDownSelect(a){for(var b in gSelectComponent)if(gOriginalSelectComponent[b]!=gSelectComponent[b])return 1;return"CALENDAR"==a&&gSelectCalendarType!=previousSelectCalendarType?1:0}
function checkColorUpdate(a){var b=0;switch(a){case "CALENDAR":case "COUNTDOWN":if(previousUserMessageColor!=userMessageColor||previousUserBackgroundColor!=userBackgroundColor||previousUserThinOutlineColor!=userThinOutlineColor||previousUserThickOutlineColor!=userThickOutlineColor||previousUserTextColor!=userTextColor)b=1;break;case "BUTTON":if(previousUserBackgroundColor!=userBackgroundColor||previousUserMessageColor!=userMessageColor||previousTextButtonSize!=textButtonSize||previousTextButtonWidget!=
textButtonWidget)b=1}return b}
function eventColor(){userMessageColor=eventUserMessageColor;userTextColor=eventUserTextColor;userBackgroundColor=eventUserBackgroundColor;userThinOutlineColor=eventUserThinOutlineColor;userThickOutlineColor=eventUserThickOutlineColor;document.getElementById("choose_text_color").style.background=affectBackgroundColor(eventUserMessageColor);document.getElementById("choose_text_other_color").style.background=affectBackgroundColor(eventUserTextColor);document.getElementById("choose_background_color").style.background=affectBackgroundColor(eventUserBackgroundColor);
document.getElementById("choose_thin_color").style.background=affectBackgroundColor(eventUserThinOutlineColor);document.getElementById("choose_thick_color").style.background=affectBackgroundColor(eventUserThickOutlineColor);updateWidgetColor()}
function updateWidgetColor(){switch(currentWidget){case "COUNTDOWN":case "COUNTDOWN-IFRAME":case "CALENDAR-IFRAME":case "CALENDAR":if("COUNTDOWN"==currentWidget||"CALENDAR"==currentWidget)document.getElementById("widget_text_color").value=userMessageColor,document.getElementById("widget_text_other_color").value=userTextColor,document.getElementById("widget_background_color").value=userBackgroundColor,document.getElementById("widget_thin_outline").value=userThinOutlineColor,document.getElementById("widget_thick_outline").value=
userThickOutlineColor;if("COUNTDOWN"==currentWidget||"COUNTDOWN-IFRAME"==currentWidget)changeStyle("#ebcountdown","background-color",userThickOutlineColor),changeStyle("#ebcountdown .registernowbutton a:hover","background-color",userThickOutlineColor),changeStyle("#ebcountdown .calshadow","border-bottom","1px "+userThickOutlineColor+" solid"),changeStyle("#ebcountdown","border-color",userThickOutlineColor),changeStyle("#ebcountdown .innerbackground","border-color",userThinOutlineColor),changeStyle("#countdown h1",
"color",userThinOutlineColor),changeStyle("#countdown h2","color",userThinOutlineColor),changeStyle("#countdown p","color",userThinOutlineColor),changeStyle("#ebcountdown .calshadow","border-top","1px "+userThinOutlineColor+" solid"),changeStyle("#ebcountdown .calshadow","border-bottom","1px "+userThinOutlineColor+" solid"),changeStyle("#ebcountdown a, a:active, a:visited","color",userMessageColor),changeStyle("#ebcountdown .registernowbutton a:hover","color",userMessageColor),changeStyle("#ebcountdown .registernowbutton a",
"background-color",userMessageColor),changeStyle("#ebcountdown .innerbackground","background-color",userBackgroundColor),changeStyle("#ebcountdown .registernowbutton a","color",userBackgroundColor),"COUNTDOWN"==currentWidget&&(document.getElementById("ebcountdown").style.backgroundColor=userThickOutlineColor);else if("CALENDAR"==currentWidget||"CALENDAR-IFRAME"==currentWidget)document.getElementById("currentMonth").style.color=userTextColor,updateCalendarNavigation(gCurrentCalendarDate),changeStyle("#monthcontainer a:hover",
"background-color",userThickOutlineColor),changeStyle("#ebcalendar .registernowbutton a:hover","background-color",userThickOutlineColor),document.getElementById("ebcalendar").style.backgroundColor=userThickOutlineColor,ie6?(document.getElementById("calendarbackground").style.backgroundColor=userBackgroundColor,changeStyle("#ebcalendar","background-color",userBackgroundColor),changeStyle("#calendarbackground","background-color",userBackgroundColor),changeStyle("div>#calendarbackground","background-color",
userBackgroundColor)):(document.getElementById("calendarbackground").style.backgroundColor=userThickOutlineColor,document.getElementById("calendarbackground").style.borderTop="1px "+userThinOutlineColor+" solid",changeStyle("#ebcalendar","background-color",userThickOutlineColor),changeStyle("#calendarbackground ul li","border-right","1px "+userThickOutlineColor+" solid"),changeStyle("#ebcalmultipledates ul","border-bottom","1px "+userThickOutlineColor+" solid"),changeStyle("#ebcaleventlist .ebcaleventdivider",
"border-bottom","1px "+userThickOutlineColor+" solid"),changeStyle("#ebcalendar .calshadow","border-top","1px "+userThinOutlineColor+" solid")),changeStyle("#ebcalmultipledates ul li a:hover","background-color",userMessageColor),changeStyle("#ebcalendar a, a:active, a:visited, #ebcalmultipledates","color",userMessageColor),changeStyle("#monthcontainer","color",userTextColor),changeStyle("#monthcontainer a:hover","color",userMessageColor),changeStyle("#calendarbackground ul","color",userTextColor),
changeStyle("#calendarbackground ul li a:hover","color",userMessageColor),changeStyle("#calendarbackground ul li a","background-color",userMessageColor),changeStyle("#ebcalendar .registernowbutton a:hover","color",userMessageColor),changeStyle("#ebcalendar .registernowbutton a","background-color",userMessageColor),changeStyle("#ebcalmultipledates h3","color",userTextColor),changeStyle("#ebcalmultipledates h3","border-bottom",userThinOutlineColor),changeStyle("#dayscontainer ul","color",userThinOutlineColor),
changeStyle("#ebcalendar .innerbackground","border","1px "+userThinOutlineColor+" solid"),changeStyle("#ebcalmultipledates ul li","border-color",userThinOutlineColor),changeStyle("#ebcaleventlist .ebcaleventdivider","border-top",userThinOutlineColor),changeStyle("#monthcontainer a","background-color",userThinOutlineColor),changeStyle("#monthcontainer a:hover","background-color",userThickOutlineColor),document.getElementById("calendarbackground").style.borderTop="1px "+userThinOutlineColor+" solid",
document.getElementById("calendarbackground").style.borderBottom="1px "+userThinOutlineColor+" solid",changeStyle("#ebcalendar .innerbackground","background-color",userBackgroundColor),changeStyle("#calendarbackground ul li a:hover","background-color",userBackgroundColor),changeStyle("#ebcalendar .registernowbutton a","color",userBackgroundColor),changeStyle("#monthcontainer a","color",userBackgroundColor),changeStyle("#calendarbackground ul li a","color",userBackgroundColor),changeStyle("#ebcalmultipledates ul li a:hover",
"color",userBackgroundColor);document.getElementById("display_eventname").style.color=userTextColor;document.getElementById("display_eventdate").style.color=userTextColor;document.getElementById("display_eventvenue").style.color=userTextColor;document.getElementById("display_eventlocation").style.color=userTextColor;document.getElementById("display_eventtweeter").style.color=userTextColor;break;case "TEXTLINK":document.getElementById("eventName").style.color=userMessageColor}}
function countDownInitProcess(a){"HOURS"==a&&changeStyle("#countdown h1","font-size","56px")}function setMessage(a){a&&(""==a.value||a.value==defaultFieldMessages[a.id]?(a.className="textbox_empty",a.value=defaultFieldMessages[a.id]):a.className="textbox")}function clearMessage(a){a&&a.value==defaultFieldMessages[a.id]&&(a.className="textbox",a.value="")}function setDefaultFieldMessages(){for(key in defaultFieldMessages)(field=document.getElementById(key))&&setMessage(field)}
var typePadApiKey="52616e646f6d495600c4316be7f79ce474401d6b72fcefdb143b4c5dca07173469f85270b2115ebfa8ecca100cfc4b0170b391b34bafb8bf",wordPressApiKey="09f4a8dfa659";function postMyspace(a,b,c,d){if("CALENDAR"==c||"COUNTDOWN"==c)b+="Simple";b=encodeURIComponent(document.getElementById(b).value+d);a=encodeURIComponent(document.getElementById(a).value);a="http://www.myspace.com/Modules/PostTo/pages/?l=1&u="+b+("?t="+a+"&c="+a);window.open(a)}
function postLinkedIn(a,b,c,d){a=document.getElementById(a).value;d=document.getElementById(b).value+d;b=a;document.getElementById("descEvent")&&(b=document.getElementById("descEvent").value);d="http://www.linkedin.com/shareArticle?mini=true&url="+encodeURIComponent(d);d+="&title="+encodeURIComponent(a)+"&source=Eventbrite";d+="&summary="+encodeURIComponent(b);window.open(d)}
function postTwitter(a,b){var c=document.getElementById(a).value;document.getElementById(b);c="http://twitter.com/home?status="+encodeURIComponent(c)+" -- "+encodeURIComponent(gEventUrl+"tw");window.open(c)}function postDigg(a,b,c,d){a=document.getElementById(a).value;b=document.getElementById(b).value+d;b="http://digg.com/submit?phase=2&url="+encodeURIComponent(b);b+="&title="+encodeURIComponent(a);window.open(b)}
function postReddit(a,b,c,d){a=document.getElementById(a).value;b=document.getElementById(b).value+d;b="http://reddit.com/submit?url="+encodeURIComponent(b);b+="&title="+encodeURIComponent(a);window.open(b)}
function postTypePad(a,b,c,d){a=document.getElementById(a).value;b=document.getElementById(b).value+d;d="https://www.typepad.com/t/app/weblog/design/widgets?service_key="+typePadApiKey;d+="&service=EventBrite&service_name=EventBrite";d+="&service_url=http://www.eventbrite.com";d+="&return_url=http://www.eventbrite.com";d+="&long_name="+encodeURIComponent(a);d+="&short_name="+encodeURIComponent(a);d+="&content="+encodeURIComponent(b);window.open(d)}
function postFacebook(a,b,c,d){document.getElementById(a);a=document.getElementById(b).value+d;a="http://www.facebook.com/sharer.php?u="+a+"&from_posted=1";window.open(a)}function loginGoogleAccount(){google.load("gdata","1.x",{packages:["blogger"]})}function logMeIn(){scope="http://www.blogger.com/feeds/";googleToken=google.accounts.user.login(scope)}function setupMyService(){googleMyServices||(googleMyServices=new google.gdata.blogger.BloggerService("GoogleInc-jsguide-1.0"),logMeIn())}
function getBloggerPost(){googleMyServices.getBlogFeed("http://www.blogger.com/feeds/default/blogs",function(a){a=a.feed.getEntries();a.length&&(a=a[0].getEntryPostLink().getHref(),window.open(a,"Your Blog"))},function(a){alert(a)})}
function postBlogger(a,b,c){setupMyService();var d=document.getElementById(a).value,e=document.getElementById(b).value+c,g=function(a){var b=new google.gdata.blogger.BlogPostEntry({title:{type:"text",text:d},content:{type:"text",text:e},categories:[{scheme:"http://www.blogger.com/atom/ns#",term:"Label1"},{scheme:"http://www.blogger.com/atom/ns#",term:"Label2"}]});a.feed.insertEntry(b,function(){alert(interpolate(gettext("The %(current_widget)s's Widget has been successfully posted to Blogger"),{current_widget:currentWidget},
!0));getBloggerPost()},k)},k=function(a){alert(a)};googleMyServices.getBlogFeed("http://www.blogger.com/feeds/default/blogs",function(a){a=a.feed.getEntries();a.length&&(a=a[0].getEntryPostLink().getHref(),googleMyServices.getBlogPostFeed(a,g,k))},k)}
function updateCountdownWidget(a,b){var c="display_"+a,d="post_"+a;if(1==gSelectComponent[a]&&!b||0==gSelectComponent[a]&&b){gSelectComponent[a]=0;document.getElementById(c).style.display="none";try{document.getElementById(a).checked=""}catch(e){}}else if(0==gSelectComponent[a]&&!b||1==gSelectComponent[a]&&b){gSelectComponent[a]=1;document.getElementById(c).style.display="block";try{document.getElementById(a).checked="checked"}catch(g){}}document.getElementById(d).value=gSelectComponent[a];b||(document.getElementById("iframeCode").value=
"")}function initCountDownSelect(){for(var a in gSelectComponent)gOriginalSelectComponent[a]=gSelectComponent[a],1==gSelectComponent[a]?document.getElementById(a)&&(document.getElementById(""+a).checked="checked"):document.getElementById(a)&&(document.getElementById(""+a).checked="")}function changeStyle(a,b,c){jQuery(a).css(b,c)}
function initCalendar(a,b,c){var d=new Date(b+"/"+a+"/01"),e=0==firstWeekDay?d.getDay()-1:d.getDay();0>e&&(e+=7);var g=nbDaysPerMonth(a,b);document.getElementById("currentMonth").innerHTML=monthNames[a-1]+" "+b;for(var k=0;42>k;k++)valueDay="day_"+k,document.getElementById(valueDay).innerHTML="",document.getElementById(valueDay).style.display="block";for(var h=0,p=d=0,m="",t={},r={},u=[],x=[],y=[],l=0,v={},w={},n=new Date,n=new Date(n.getFullYear(),n.getMonth(),n.getDate()),s=!1,k=e;42>k;k++)if(l=
0,h+=1,h<=g)if(valueDay="day_"+k,currentDayMonth=b+"/"+PadDigits(a,2)+"/"+PadDigits(h,2),idxTabEventdate=gTabEventDate.indexOf(currentDayMonth),0<=idxTabEventdate)if(1<gTabNbrEventDate[idxTabEventdate]&&(idxOrg=searchForOrganizer(gSelectCurrentOrganizer,currentDayMonth),l=1,0<idxOrg&&(idxTabEventdate=idxOrg-1)),0==gTabHasPublicEventsDate[idxTabEventdate]&&!showPrivateEvents)document.getElementById(valueDay).innerHTML=h;else{e=null;if(""!=c)for(var j in gTabEventOrganizerIdReference){var m=gTabEventOrganizerIdReference[j],
f=gTabEventDateReference[j],q=gTabEventDateListReference[j],z=gTabEventListedReference[j];if(showPrivateEvents||1==z)if(m==gFilterByOrganizer&&(f==currentDayMonth||0<=q.indexOf(currentDayMonth)))e=j}else""==c&&(e=gTabEventDatePublicEID[idxTabEventdate]);e?(f={},q=m="",j=e,f.eid=j,f.name=gTabEventReference[j],f.date=currentDayMonth,f.oid=gTabEventOrganizerIdReference[j],f.oname=gTabEventOrganizerReference[j],f.multiEvent=l,f.valueDay=valueDay,f.sig=gTabEventSigReference[j],v=f,s||(e=new Date(currentDayMonth),
n.getTime()<=e.getTime()&&(w=f,s=!0)),""!=f.oname&&(m=gettext("Organized by")+" "+f.oname),q=1==l?interpolate(ngettext("%(number_events)s event has been found for the same date","%(number_events)s events have been found for the same date",f.date),{number_events:gTabNbrEventDate[idxTabEventdate]},!0):f.name+" "+m,document.getElementById(valueDay).innerHTML='<a href="javascript:selDateEvent('+j+",'"+currentDayMonth+"',"+l+",'"+c+"','"+valueDay+"',"+showPrivateEvents+",'"+f.sig+'\') ;" title="'+q+'" >'+
h+"</a>",r[currentDayMonth]=f,"*"!=t[j]&&(t[j]="*",u.push(j),x.push(currentDayMonth),y.push(l)),p+=parseInt(gTabNbrEventDate[idxTabEventdate]),d+=1):document.getElementById(valueDay).innerHTML=h}else document.getElementById(valueDay).innerHTML=h;else{for(b=k;42>b;b++)valueDay="day_"+b,document.getElementById(valueDay).style.display="none";break}document.getElementById("currentMonth").title=interpolate(ngettext("%(number_events)s Event found on %(month)s","%(number_events)s Events found on %(month)s",
p),{number_events:p,month:monthNames[a-1]},!0);0<u.length?(displayElement("event_window_register","block"),a={},a=selectedEventDate in r?r[selectedEventDate]:s?w:v,selDateEvent(a.eid,a.date,a.multiEvent,c,"",showPrivateEvents,a.sig)):(displayElement("event_window_register","none"),displayElement("ebcalmultipledates","none"));document.getElementById("rightcol")&&(document.getElementById("rightcol").style.display="block");return d}
function displayElement(a,b){var c=document.getElementById(a);c&&(c.style.display=b)}function searchForOrganizer(a,b){for(var c=0;c<gTabEventDate.length;c++)if(gTabEventDate[c]==b&&gTabEventDateOrg[c]==a)return c+1;return 0}
function computeMinmaxEventDate(a){var b="",c="",c=[],b=0;if(a){for(var d in gTabEventReference)gTabEventOrganizerIdReference[d]==a&&(b+=1,""==gTabEventDateListReference[d]?c.push(gTabEventDateReference[d]):c=c.concat(gTabEventDateListReference[d].split(",")));if(0<b)return b=new Date(c.min()),gMinEventDate=b.getFullYear()+"/"+PadDigits(b.getMonth()+1,2),c=new Date(c.max()),gMaxEventDate=c.getFullYear()+"/"+PadDigits(c.getMonth()+1,2),b}else return b=new Date(gTabEventDate.min()),gMinEventDate=b.getFullYear()+
"/"+PadDigits(b.getMonth()+1,2),c=new Date(gTabEventDate.max()),gMaxEventDate=c.getFullYear()+"/"+PadDigits(c.getMonth()+1,2),b}
function calendarType(a,b){var c=0;"ALL"==a||""==a?(gSelectCalendarType="ALL",gFilterByOrganizer="",document.getElementById("all_my_events")&&(document.getElementById("all_my_events").checked="checked"),gDateEvent=computeMinmaxEventDate(),c=initCalendar(gDateEvent.getMonth()+1,gCurrentYear,gFilterByOrganizer),0<gTotalFoundLiveEvent&&checkNextValidMonth(c)):(gSelectCalendarType="ORG",gFilterByOrganizer=gSelectCurrentOrganizer,document.getElementById("by_organizer")&&(document.getElementById("by_organizer").checked=
"checked"),(gDateEvent=computeMinmaxEventDate(gFilterByOrganizer))?(c=initCalendar(gCurrentMonth,gCurrentYear,gFilterByOrganizer),0<gTotalFoundLiveEvent&&checkNextValidMonth(c)):0==gTotalFoundLiveEvent&&initCalendar(gCurrentMonth,gCurrentYear,gFilterByOrganizer));"CALENDAR"==currentWidget&&(document.getElementById("widget_calendar_type").value=gSelectCalendarType);updateCalendarNavigation(gCurrentCalendarDate);b||(document.getElementById("iframeCode").value="")}
function checkNextValidMonth(a){0==a&&(a=changeMonth("NEXT","check"),0==a&&(gCurrentYear=gDateEvent.getFullYear(),gCurrentMonth=gDateEvent.getMonth()+1,initCalendar(gCurrentMonth,gCurrentYear,gFilterByOrganizer),gCurrentCalendarDate=new Date(formatCalDate(gCurrentYear,gCurrentMonth,"long")),updateCalendarNavigation(gCurrentCalendarDate)))}
function changeMonth(a,b){var c=0,d=1,e=formatCalDate(gCurrentYear,gCurrentMonth);for("PREV"==a&&(d=-1);e<=gMaxEventDate&&e>=gMinEventDate;)if(c=addMonth(new Date(formatCalDate(gCurrentYear,gCurrentMonth,"long")),d),gCurrentYear=c.getFullYear(),gCurrentMonth=c.getMonth()+1,e=formatCalDate(gCurrentYear,gCurrentMonth),c=initCalendar(gCurrentMonth,gCurrentYear,gFilterByOrganizer),0<c){gLastMonth=gCurrentMonth;gLastYear=gCurrentYear;gCurrentCalendarDate=new Date(formatCalDate(gCurrentYear,gCurrentMonth,
"long"));updateCalendarNavigation(gCurrentCalendarDate);break}else if(e>gMaxEventDate||e<gMinEventDate){gCurrentMonth=gLastMonth;gCurrentYear=gLastYear;gCurrentCalendarDate=new Date(formatCalDate(gCurrentYear,gCurrentMonth,"long"));c=initCalendar(gCurrentMonth,gCurrentYear,gFilterByOrganizer);updateCalendarNavigation(gCurrentCalendarDate);break}if(b)return c}function formatCalDate(a,b,c){var d="";c&&(d="/01");return a+"/"+PadDigits(b,2)+d}
function updateCalendarNavigation(a){a=formatCalDate(a.getFullYear(),a.getMonth()+1);document.getElementById("PREV_button").innerHTML="&lt;";document.getElementById("NEXT_button").innerHTML="&gt;";document.getElementById("NEXT_button").href="javascript: changeMonth('NEXT');";document.getElementById("PREV_button").href="javascript: changeMonth('PREV');";document.getElementById("NEXT_button").style.backgroundColor=userThinOutlineColor;document.getElementById("PREV_button").style.backgroundColor=userThinOutlineColor;
if(a>=gMaxEventDate||0==gTotalFoundLiveEvent)document.getElementById("NEXT_button").innerHTML="",document.getElementById("NEXT_button").href="javascript:void(0);",document.getElementById("NEXT_button").style.backgroundColor=userBackgroundColor;if(a<=gMinEventDate||0==gTotalFoundLiveEvent)document.getElementById("PREV_button").innerHTML="",document.getElementById("PREV_button").href="javascript:void(0);",document.getElementById("PREV_button").style.backgroundColor=userBackgroundColor}
function addMonth(a,b){var c=new Date(a),d=c.getMonth()+1,c=c.getFullYear(),d=d+b;0>=d?(d=12-(b+1),c-=1):12<d&&(d-=12,c+=1);return new Date(c+"/"+d+"/01")}function createWidget(){gClickOnCreateWidget=1;document.getElementById("submitted").value="1";document.widgetForm.target="_top";document.widgetForm.submit()}
function clsEventData(a){document.getElementById("display_eventname").style.display=a;document.getElementById("display_eventdate").style.display=a;document.getElementById("display_eventvenue").style.display=a;document.getElementById("display_eventlocation").style.display=a;document.getElementById("display_eventtweeter").style.display=a}
function selDateEvent(a,b,c,d,e,g,k){if(gLastDisplayEvent!=a||gLastDisplayDateEvent!=b||gLastDisplayOrg!=d||gLastDisplayListedType!=g){var h="";gLastCalendarDivSelected=e;1==c&&(h="&multevent=1");g&&(h=h+"&showPrivate=1"+("&sig="+k));""!=d&&(h+="&org="+d);c="eid="+encodeURIComponent(a)+"&date="+encodeURIComponent(b)+h;jQuery.ajax({url:"/eventcalendar",type:"POST",data:c,success:function(a,b,c){displayCalendarEvent(c)},error:noEventData});gLastDisplayEvent=a;gLastDisplayDateEvent=b;gLastDisplayOrg=
d;gLastDisplayListedType=g}}
function saveWidgetSettings(a,b){var c="eid="+encodeURIComponent(a),c=c+("&widget="+encodeURIComponent(b));switch(b){case "CALENDAR":case "COUNTDOWN":var c=c+("&widget_calendar_type="+encodeURIComponent(gSelectCalendarType)),c=c+("&widget_text_color="+encodeURIComponent(userMessageColor)),c=c+("&widget_background_color="+encodeURIComponent(userBackgroundColor)),c=c+("&widget_thin_outline="+encodeURIComponent(userThinOutlineColor)),c=c+("&widget_thick_outline="+encodeURIComponent(userThickOutlineColor)),c=
c+("&widget_text_other_color="+encodeURIComponent(userTextColor)),d;for(d in gSelectComponent)c+="&post_"+d+"="+gSelectComponent[d];previousUserMessageColor=userMessageColor;previousUserBackgroundColor=userBackgroundColor;previousUserThinOutlineColor=userThinOutlineColor;previousUserThickOutlineColor=userThickOutlineColor;previousUserTextColor=userTextColor;for(d in gSelectComponent)gOriginalSelectComponent[d]=gSelectComponent[d];break;case "BUTTON":c+=EB.ButtonWidget.saveWidgetParams()}jQuery.ajax({url:"/widgetsettings",
type:"POST",data:c,success:widgetSaved,error:noEventData})}function widgetSaved(){document.getElementById("embedpanel").scrollIntoView(!0)}
function displayCalendarEvent(a){if(a.responseText&&(objEvent=JSON.parse(a.responseText)))gNbrEventByDate=1,gEventName=objEvent.name,gSelectCurrentEID=objEvent.eid,gEventLogo=objEvent.logo,gEventName=objEvent.name,gEventVenue=objEvent.venue,gEventDates=objEvent.date,gEventShortDates=objEvent.dateshort,gEventAddress=objEvent.address,gEventUrl=objEvent.regurl,gTwitterUrl=objEvent.twitter,gLocationMapUrl=objEvent.mapurl,1<parseInt(objEvent.nbrevent)&&(gNbrEventByDate=objEvent.nbrevent,gArrayEID=objEvent.listeid,
gArrayEventName=objEvent.listname,gArrayEventTime=objEvent.listtime,gArrayEventOrganizer=objEvent.listorg,gArrayEventLocation=objEvent.location),affectEbCalendar()}function noEventData(){alert("No Event Found");return!1}
function affectEbCalendar(){for(var a=0;a<gMaxEventPerDay;a++)valueDay="event_"+a,document.getElementById(valueDay).innerHTML="",document.getElementById(valueDay).style.display="none";document.getElementById("event_window_register").style.display="block";document.getElementById("ebcalmultipledates").style.display="none";""!=gLastCalendarDivSelected&&(document.getElementById(gLastCalendarDivSelected).title="");if(1<gNbrEventByDate){""!=gLastCalendarDivSelected&&(document.getElementById(gLastCalendarDivSelected).title=
interpolate(ngettext("%(number_events)s event has been found for the same date","%(number_events)s events have been found for the same date",gNbrEventByDate),{number_events:gNbrEventByDate},!0));document.getElementById("event_window_register").style.display="none";document.getElementById("ebcalmultipledates").style.display="block";document.getElementById("mult_event_title").innerHTML=gettext("Events on ")+gEventShortDates;gNbrEventByDate>gMaxEventPerDay&&(gNbrEventByDate=gMaxEventPerDay);for(a=0;a<
gNbrEventByDate;a++)orgTitle="",""!=gArrayEventOrganizer[a]&&(orgTitle=" "+gettext("Organized By")+" "+gArrayEventOrganizer[a]),valueDay="event_"+a,EventUrl='<a href="'+baseUrl+"/event/"+gArrayEID[a]+'?ref=ecal" target="_blank" class="active" title="'+gArrayEventName[a]+orgTitle+'" >',EventUrl+="<span>"+gettext("Register now for:")+"</span><br />"+gArrayEventName[a]+"<br />",EventUrl+="<span>"+gArrayEventTime[a],""!=gArrayEventLocation[a]&&" "!=gArrayEventLocation[a]&&(EventUrl+=" / "+gArrayEventLocation[a]),
EventUrl+="</span>",document.getElementById(valueDay).innerHTML=EventUrl,document.getElementById(valueDay).style.display="block"}eventLogo=1==gSelectComponent.eventlogo?""!=gEventLogo&&null!=gEventLogo?'<a href="'+gEventUrl+'" id="display_eventlogo" target="_blank" ><img src="'+gEventLogo+'" width="173" /></a>':"":"";document.getElementById("display_eventdate").innerHTML=gEventDates;document.getElementById("display_eventregister").href=gEventUrl;document.getElementById("display_eventlocation").href=
gLocationMapUrl;document.getElementById("display_eventvenue").href=gLocationMapUrl;document.getElementById("display_eventname").href=gEventUrl;document.getElementById("display_eventlogo").innerHTML=eventLogo;document.getElementById("display_eventname").innerHTML=gEventName;document.getElementById("display_eventlocation").innerHTML=gEventAddress;document.getElementById("display_eventvenue").innerHTML=gEventVenue;document.getElementById("display_eventtweeter").href=gTwitterUrl}
function getRandomFooterLink(a,b){var c="eid="+encodeURIComponent(a)+"&widget="+b;jQuery.ajax({url:"/widget-footer-link",type:"POST",data:c,success:function(a,b,c){displayFooterLink(c)},error:noEventData})}function displayFooterLink(a){if(a.responseText&&(objFooter=JSON.parse(a.responseText))&&"ok"==objFooter.status)gWidgetFooterLink=objFooter.footer,document.getElementById("frt"+objFooter.eid).innerHTML=gWidgetFooterLink,embeddedCode()}
function CopyToClipboard(){document.getElementById("iframeCode").focus();document.getElementById("iframeCode").select();CopiedTxt=document.selection.createRange();CopiedTxt.execCommand("Copy");alert(gettext("The code was copied to your clipboard."))}function copyZeroClipBoard(){clip.setText(document.getElementById("iframeCode").value)}function completeCopyClip(){alert(gettext("The code was copied to your clipboard."))}function loadCopyClip(){};var gNbrEventDigits=4,gColorFooter="#ddd",gFrtDiv="div9999",gFrameID="frameId9999",gFooterDiv="frt9999",gframeDivId="frm9999",gFooterUrlDiv="ftu9999",gFooterUrlSpan="spa9999",gFooterUrlSpan2="spac9999",gSpanFooter="spuc9999",gSpanFooter2="spud9999";function regFrm(a,b,c){c||(c=gup(a.src,"eid"),c=c.substring(c.length,gNbrEventDigits+1));var d=getWidgetCode(a.src);formatDivId(c);adjustHeight=mainCustomIframe(d,a);customIframeFooter();a.style.height=b+adjustHeight+"px"}
function formatDivId(a){gFrameID="frameId"+a;gFooterDiv="ftr"+a;gFrameID="frameId"+a;gMainFrameDiv="div"+a;gFooterUrlDiv="ftu"+a;gFooterUrlSpan="spac"+a;gFooterUrlSpan2="spuc"+a;gSpanFooter="spa"+a;gSpanFooter2="spu"+a}
function customIframeFooter(){if(document.getElementById(gFooterDiv)){var a=document.getElementById(gFooterDiv);a.style.fontFamily="Helvetica, Arial";a.style.fontSize="10px";a.style.padding="5px 0 5px";a.style.margin="2px"}document.getElementById(gFooterUrlDiv)&&(a=document.getElementById(gFooterUrlDiv),a.style.color=gColorFooter,a.style.textDecoration="none",a.target="_blank");document.getElementById(gFooterUrlSpan)&&(a=document.getElementById(gFooterUrlSpan),a.style.color=gColorFooter,a.style.textDecoration=
"none",a.target="_blank");document.getElementById(gFooterUrlSpan2)&&(a=document.getElementById(gFooterUrlSpan2),a.style.color=gColorFooter,a.style.textDecoration="none",a.target="_blank");document.getElementById(gSpanFooter)&&(a=document.getElementById(gSpanFooter),a.style.color=gColorFooter);document.getElementById(gSpanFooter2)&&(a=document.getElementById(gSpanFooter2),a.style.color=gColorFooter)}
function mainCustomIframe(a,b){b.style.visibility="visible";var c=0;switch(a){case "ecal":c=adaptHeightByBrowser("ecal");b.width="220";b.marginheight="0";b.marginwidth="0";b.frameBorder="no";b.scrolling="no";if(document.getElementById(gMainFrameDiv)){var d=document.getElementById(gMainFrameDiv);d.style.width="195px";d.style.textAlign="center"}document.getElementById(gFooterDiv)&&(d=document.getElementById(gFooterDiv),d.style.width="195px",d.style.textAlign="center",d.style.margin="2px");break;case "ecount":c=
adaptHeightByBrowser("ecount");b.width="220";b.marginheight="0";b.marginwidth="0";b.frameBorder="no";b.scrolling="no";document.getElementById(gMainFrameDiv)&&(d=document.getElementById(gMainFrameDiv),d.style.width="195px",d.style.textAlign="center");document.getElementById(gFooterDiv)&&(d=document.getElementById(gFooterDiv),d.style.width="195px",d.style.textAlign="center",d.style.margin="2px");break;case "widget":case "etckt":c=adaptHeightByBrowser("etckt");b.width="100%";b.marginheight="5";b.marginwidth=
"5";b.vspace="0";b.hspace="0";b.scrolling="auto";b.allowtransparency="true";document.getElementById(gMainFrameDiv)&&(d=document.getElementById(gMainFrameDiv),d.style.width="100%",d.style.textAlign="left");document.getElementById(gFooterDiv)&&(d=document.getElementById(gFooterDiv),d.style.width="100%",d.style.textAlign="left");break;case "eweb":c=adaptHeightByBrowser("eweb"),b.width="100%",b.marginheight="5",b.marginwidth="5",b.vspace="0",b.hspace="0",b.scrolling="auto",b.allowtransparency="true",
document.getElementById(gMainFrameDiv)&&(d=document.getElementById(gMainFrameDiv),d.style.width="100%",d.style.textAlign="left"),document.getElementById(gFooterDiv)&&(d=document.getElementById(gFooterDiv),d.style.width="100%",d.style.textAlign="left")}return c}function gup(a,b){b=b.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var c=RegExp("[\\?&]"+b+"=([^&#]*)").exec(a);return null==c?"":c[1]}
function getWidgetCode(a){return 0<=a.indexOf("/calendar")?"ecal":0<=a.indexOf("/countdown")?"ecount":0<=a.indexOf("/event")?"eweb":0<=a.indexOf("/tickets")?"etckt":"widget"}
function adaptHeightByBrowser(a){var b=navigator.appVersion,c=navigator.appName,d=navigator.platform;if(0<=b.indexOf("Mac")||0<=b.indexOf("Safari"))switch(a){case "ecal":return 25;case "etckt":return 10;case "ecount":return 25;case "eweb":return 10}if(0<=c.indexOf("Netscape")&&0<=d.indexOf("Win32"))switch(a){case "ecal":return 20;case "etckt":return 25;case "ecount":return 10;case "eweb":return 10}if(0<=b.indexOf("MSIE")&&0<=d.indexOf("Win32"))switch(a){case "ecal":return 65;case "etckt":return 30;
case "ecount":return 50;case "eweb":return 40}return 20};
